#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path
from urllib.request import Request, urlopen

from data_update_utils import format_path_for_log, load_countries

ROOT_DIR = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT_DIR / "src" / "countryLanguages.js"
SOURCE_URL = "https://restcountries.com/v3.1/all?fields=cca3,languages"
SOURCE_CODE_OVERRIDES = {
    "KOS": "UNK",
    "WBG": "PSE",
}


def main() -> None:
    language_map = fetch_language_map()
    countries = load_countries()
    output: dict[str, list[str]] = {}
    missing: list[str] = []

    for country in countries:
        code = country["code"]

        if code == "G001":
            output[code] = []
            continue

        source_code = SOURCE_CODE_OVERRIDES.get(code, code)
        languages = language_map.get(source_code, [])
        output[code] = languages

        if not languages:
            missing.append(code)

    OUTPUT_PATH.write_text(render_module(output), encoding="utf-8")
    print(f"Wrote {format_path_for_log(OUTPUT_PATH)}")
    print(f"Countries and territories: {len(output)}")
    print(f"Missing language entries: {len(missing)}")

    if missing:
        print(f"Missing codes: {', '.join(missing)}")


def fetch_language_map() -> dict[str, list[str]]:
    request = Request(SOURCE_URL, headers={"User-Agent": "Codex country language updater"})
    print(f"Fetching {SOURCE_URL}")

    with urlopen(request, timeout=120) as response:
        countries = json.loads(response.read().decode("utf-8"))

    return {
        country["cca3"]: sorted(set(country.get("languages", {}).values()))
        for country in countries
        if country.get("cca3")
    }


def render_module(language_map: dict[str, list[str]]) -> str:
    lines = [
        "// Generated by scripts/update-country-languages.py from REST Countries.",
        "export const officialLanguagesByCountryCode = {",
    ]

    for code, languages in language_map.items():
        lines.append(f"  {json.dumps(code)}: {json.dumps(languages, ensure_ascii=False)},")

    lines.append("};")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    main()
