export const seriesConfigs = [
  {
    id: "gdp",
    canvasId: "gdpChart",
    chartCardId: "gdpChartCard",
    overlayId: "gdpOverlay",
    statusId: "gdpStatus",
    dataSource: "IMF World Economic Outlook",
    dataset: "WEO",
    indicatorCode: "NGDPD",
    staticDataPath: "./data/weo/current-prices.json",
    sourceUrl: "https://data.imf.org/-/media/iData/External-Storage/Documents/2F78EE59F79143A7921E5E203D3AAA80/en/WEOApr2026all.xlsx",
    startYear: 1980,
    endYear: 2026,
    titleTemplate: "Nominal GDP",
    subtitle: "IMF World Economic Outlook, 1980-2026",
    unitLabel: "Billions of U.S. dollars",
    currencyCode: "USD",
    currencyLabel: "Currency: USD",
    tooltipPrefix: "$",
    valueScaleMode: "gdpMagnitude",
    maximumFractionDigits: 2,
  },
  {
    id: "gdpPerCapita",
    canvasId: "gdpPerCapitaChart",
    chartCardId: "gdpPerCapitaChartCard",
    overlayId: "gdpPerCapitaOverlay",
    statusId: "gdpPerCapitaStatus",
    dataSource: "IMF World Economic Outlook",
    dataset: "WEO",
    indicatorCode: "NGDPDPC",
    staticDataPath: "./data/weo/current-prices.json",
    sourceUrl: "https://data.imf.org/-/media/iData/External-Storage/Documents/2F78EE59F79143A7921E5E203D3AAA80/en/WEOApr2026all.xlsx",
    startYear: 1980,
    endYear: 2026,
    titleTemplate: "Nominal GDP per capita",
    subtitle: "IMF World Economic Outlook, 1980-2026",
    unitLabel: "U.S. dollars per person",
    currencyCode: "USD",
    currencyLabel: "Currency: USD",
    tickPrefix: "$",
    tooltipPrefix: "$",
    tooltipUnit: "",
    maximumFractionDigits: 0,
  },
  {
    id: "gdpNational",
    canvasId: "gdpNationalChart",
    chartCardId: "gdpNationalChartCard",
    overlayId: "gdpNationalOverlay",
    statusId: "gdpNationalStatus",
    dataSource: "IMF World Economic Outlook",
    dataset: "WEO",
    indicatorCode: "NGDP",
    staticDataPath: "./data/weo/current-prices.json",
    sourceUrl: "https://data.imf.org/-/media/iData/External-Storage/Documents/2F78EE59F79143A7921E5E203D3AAA80/en/WEOApr2026all.xlsx",
    startYear: 1980,
    endYear: 2026,
    titleTemplate: "Nominal GDP",
    subtitle: "IMF World Economic Outlook, 1980-2026",
    unitLabel: "Billions of national currency",
    currencyLabel: "Currency: local",
    usesCountryCurrency: true,
    valueScaleMode: "nationalCurrencyMagnitude",
    maximumFractionDigits: 2,
  },
  {
    id: "realGdp",
    canvasId: "realGdpChart",
    chartCardId: "realGdpChartCard",
    overlayId: "realGdpOverlay",
    statusId: "realGdpStatus",
    dataSource: "IMF World Economic Outlook",
    dataset: "WEO",
    indicatorCode: "NGDP_R",
    staticDataPath: "./data/weo/current-prices.json",
    sourceUrl: "https://data.imf.org/-/media/iData/External-Storage/Documents/2F78EE59F79143A7921E5E203D3AAA80/en/WEOApr2026all.xlsx",
    startYear: 1980,
    endYear: 2026,
    titleTemplate: "Real GDP",
    subtitle: "IMF World Economic Outlook, 1980-2026",
    unitLabel: "Billions of constant national currency",
    currencyLabel: "Currency: local",
    usesCountryCurrency: true,
    valueScaleMode: "nationalCurrencyMagnitude",
    maximumFractionDigits: 2,
  },
  {
    id: "gdpGrowth",
    canvasId: "gdpGrowthChart",
    chartCardId: "gdpGrowthChartCard",
    overlayId: "gdpGrowthOverlay",
    statusId: "gdpGrowthStatus",
    dataSource: "IMF World Economic Outlook",
    dataset: "WEO",
    indicatorCode: "NGDP_RPCH",
    staticDataPath: "./data/weo/current-prices.json",
    sourceUrl: "https://data.imf.org/-/media/iData/External-Storage/Documents/2F78EE59F79143A7921E5E203D3AAA80/en/WEOApr2026all.xlsx",
    startYear: 1980,
    endYear: 2026,
    titleTemplate: "Real GDP Growth Rate",
    subtitle: "IMF World Economic Outlook, 1980-2026",
    unitLabel: "Percent change",
    currencyLabel: "Unit: %",
    suffix: "%",
    suffixSpacing: "",
    maximumFractionDigits: 1,
  },
  {
    id: "inflationRate",
    canvasId: "inflationRateChart",
    chartCardId: "inflationRateChartCard",
    overlayId: "inflationRateOverlay",
    statusId: "inflationRateStatus",
    dataSource: "IMF World Economic Outlook",
    dataset: "WEO",
    indicatorCode: "PCPIPCH",
    staticDataPath: "./data/weo/current-prices.json",
    sourceUrl: "https://data.imf.org/-/media/iData/External-Storage/Documents/2F78EE59F79143A7921E5E203D3AAA80/en/WEOApr2026all.xlsx",
    startYear: 1980,
    endYear: 2026,
    titleTemplate: "Inflation Rate",
    subtitle: "IMF World Economic Outlook, 1980-2026",
    unitLabel: "Percent change",
    currencyLabel: "Unit: %",
    suffix: "%",
    suffixSpacing: "",
    maximumFractionDigits: 1,
  },
  {
    id: "gdpNationalPerCapita",
    canvasId: "gdpNationalPerCapitaChart",
    chartCardId: "gdpNationalPerCapitaChartCard",
    overlayId: "gdpNationalPerCapitaOverlay",
    statusId: "gdpNationalPerCapitaStatus",
    dataSource: "IMF World Economic Outlook",
    dataset: "WEO",
    indicatorCode: "NGDPPC",
    staticDataPath: "./data/weo/current-prices.json",
    sourceUrl: "https://data.imf.org/-/media/iData/External-Storage/Documents/2F78EE59F79143A7921E5E203D3AAA80/en/WEOApr2026all.xlsx",
    startYear: 1980,
    endYear: 2026,
    titleTemplate: "Nominal GDP per capita",
    subtitle: "IMF World Economic Outlook, 1980-2026",
    unitLabel: "National currency per person",
    currencyLabel: "Currency: local",
    usesCountryCurrency: true,
    valueScale: 1,
    maximumFractionDigits: 0,
  },
  {
    id: "realGdpPerCapita",
    canvasId: "realGdpPerCapitaChart",
    chartCardId: "realGdpPerCapitaChartCard",
    overlayId: "realGdpPerCapitaOverlay",
    statusId: "realGdpPerCapitaStatus",
    dataSource: "IMF World Economic Outlook",
    dataset: "WEO",
    indicatorCode: "NGDPRPC",
    staticDataPath: "./data/weo/current-prices.json",
    sourceUrl: "https://data.imf.org/-/media/iData/External-Storage/Documents/2F78EE59F79143A7921E5E203D3AAA80/en/WEOApr2026all.xlsx",
    startYear: 1980,
    endYear: 2026,
    titleTemplate: "Real GDP per capita",
    subtitle: "IMF World Economic Outlook, 1980-2026",
    unitLabel: "Constant national currency per person",
    currencyLabel: "Currency: local",
    usesCountryCurrency: true,
    valueScale: 1,
    maximumFractionDigits: 0,
  },
  {
    id: "ppp",
    canvasId: "pppChart",
    chartCardId: "pppChartCard",
    overlayId: "pppOverlay",
    statusId: "pppStatus",
    dataSource: "IMF World Economic Outlook",
    dataset: "WEO",
    indicatorCode: "PPPGDP",
    staticDataPath: "./data/weo/current-prices.json",
    sourceUrl: "https://data.imf.org/-/media/iData/External-Storage/Documents/2F78EE59F79143A7921E5E203D3AAA80/en/WEOApr2026all.xlsx",
    startYear: 1980,
    endYear: 2026,
    titleTemplate: "PPP GDP",
    subtitle: "IMF World Economic Outlook, 1980-2026",
    unitLabel: "Billions of international dollars",
    currencyCode: "INT$",
    currencyLabel: "Currency: international dollars",
    tooltipPrefix: "$",
    valueScaleMode: "internationalDollarMagnitude",
    maximumFractionDigits: 2,
  },
  {
    id: "pppPerCapita",
    canvasId: "pppPerCapitaChart",
    chartCardId: "pppPerCapitaChartCard",
    overlayId: "pppPerCapitaOverlay",
    statusId: "pppPerCapitaStatus",
    dataSource: "IMF World Economic Outlook",
    dataset: "WEO",
    indicatorCode: "PPPPC",
    staticDataPath: "./data/weo/current-prices.json",
    sourceUrl: "https://data.imf.org/-/media/iData/External-Storage/Documents/2F78EE59F79143A7921E5E203D3AAA80/en/WEOApr2026all.xlsx",
    startYear: 1980,
    endYear: 2026,
    titleTemplate: "PPP GDP per capita",
    subtitle: "IMF World Economic Outlook, 1980-2026",
    unitLabel: "International dollars per person",
    currencyCode: "INT$",
    currencyLabel: "Currency: international dollars",
    tickPrefix: "$",
    tooltipPrefix: "$",
    tooltipUnit: "",
    maximumFractionDigits: 0,
  },
];
