export const seriesConfigs = [
  {
    id: "gdp",
    canvasId: "gdpChart",
    chartCardId: "gdpChartCard",
    overlayId: "gdpOverlay",
    statusId: "gdpStatus",
    dataSource: "IMF World Economic Outlook",
    dataset: "WEO",
    indicatorCode: "NGDPD",
    staticDataPath: "./data/weo/current-prices.json",
    sourceUrl: "https://data.imf.org/-/media/iData/External-Storage/Documents/2F78EE59F79143A7921E5E203D3AAA80/en/WEOApr2026all.xlsx",
    startYear: 1980,
    endYear: 2026,
    titleTemplate: "Nominal GDP",
    subtitle: "IMF World Economic Outlook, 1980-2026",
    unitLabel: "Billions of U.S. dollars",
    currencyCode: "USD",
    currencyLabel: "Currency: USD",
    tooltipPrefix: "$",
    valueScaleMode: "gdpMagnitude",
    maximumFractionDigits: 2,
  },
  {
    id: "gdpPerCapita",
    canvasId: "gdpPerCapitaChart",
    chartCardId: "gdpPerCapitaChartCard",
    overlayId: "gdpPerCapitaOverlay",
    statusId: "gdpPerCapitaStatus",
    dataSource: "IMF World Economic Outlook",
    dataset: "WEO",
    indicatorCode: "NGDPDPC",
    staticDataPath: "./data/weo/current-prices.json",
    sourceUrl: "https://data.imf.org/-/media/iData/External-Storage/Documents/2F78EE59F79143A7921E5E203D3AAA80/en/WEOApr2026all.xlsx",
    startYear: 1980,
    endYear: 2026,
    titleTemplate: "Nominal GDP per capita",
    subtitle: "IMF World Economic Outlook, 1980-2026",
    unitLabel: "U.S. dollars per person",
    currencyCode: "USD",
    currencyLabel: "Currency: USD",
    tickPrefix: "$",
    tooltipPrefix: "$",
    tooltipUnit: "",
    maximumFractionDigits: 0,
  },
  {
    id: "gdpNational",
    canvasId: "gdpNationalChart",
    chartCardId: "gdpNationalChartCard",
    overlayId: "gdpNationalOverlay",
    statusId: "gdpNationalStatus",
    dataSource: "IMF World Economic Outlook",
    dataset: "WEO",
    indicatorCode: "NGDP",
    staticDataPath: "./data/weo/current-prices.json",
    sourceUrl: "https://data.imf.org/-/media/iData/External-Storage/Documents/2F78EE59F79143A7921E5E203D3AAA80/en/WEOApr2026all.xlsx",
    startYear: 1980,
    endYear: 2026,
    titleTemplate: "Nominal GDP",
    subtitle: "IMF World Economic Outlook, 1980-2026",
    unitLabel: "Billions of national currency",
    currencyLabel: "Currency: local",
    usesCountryCurrency: true,
    valueScaleMode: "nationalCurrencyMagnitude",
    maximumFractionDigits: 2,
  },
  {
    id: "gdpNationalPerCapita",
    canvasId: "gdpNationalPerCapitaChart",
    chartCardId: "gdpNationalPerCapitaChartCard",
    overlayId: "gdpNationalPerCapitaOverlay",
    statusId: "gdpNationalPerCapitaStatus",
    dataSource: "IMF World Economic Outlook",
    dataset: "WEO",
    indicatorCode: "NGDPPC",
    staticDataPath: "./data/weo/current-prices.json",
    sourceUrl: "https://data.imf.org/-/media/iData/External-Storage/Documents/2F78EE59F79143A7921E5E203D3AAA80/en/WEOApr2026all.xlsx",
    startYear: 1980,
    endYear: 2026,
    titleTemplate: "Nominal GDP per capita",
    subtitle: "IMF World Economic Outlook, 1980-2026",
    unitLabel: "National currency per person",
    currencyLabel: "Currency: local",
    usesCountryCurrency: true,
    valueScale: 1,
    maximumFractionDigits: 0,
  },
];
