import { dataSources } from "./dataSources.js";

const { weoCurrentPrices, unctadGoodsTrade, worldBankWdi, worldBankPopulation, worldBankEnvironment } = dataSources;

export const seriesConfigs = [
  {
    id: "gdp",
    canvasId: "gdpChart",
    chartCardId: "gdpChartCard",
    overlayId: "gdpOverlay",
    statusId: "gdpStatus",
    ...weoCurrentPrices,
    indicatorCode: "NGDPD",
    titleTemplate: "Nominal GDP",
    currencyCode: "USD",
    tooltipPrefix: "$",
    valueScaleMode: "gdpMagnitude",
    maximumFractionDigits: 2,
  },
  {
    id: "gdpPerCapita",
    canvasId: "gdpPerCapitaChart",
    chartCardId: "gdpPerCapitaChartCard",
    overlayId: "gdpPerCapitaOverlay",
    statusId: "gdpPerCapitaStatus",
    ...weoCurrentPrices,
    indicatorCode: "NGDPDPC",
    titleTemplate: "Nominal GDP per capita",
    currencyCode: "USD",
    tickPrefix: "$",
    tooltipPrefix: "$",
    tooltipUnit: "",
    maximumFractionDigits: 0,
  },
  {
    id: "gdpNational",
    canvasId: "gdpNationalChart",
    chartCardId: "gdpNationalChartCard",
    overlayId: "gdpNationalOverlay",
    statusId: "gdpNationalStatus",
    ...weoCurrentPrices,
    indicatorCode: "NGDP",
    titleTemplate: "Nominal GDP",
    usesCountryCurrency: true,
    valueScaleMode: "nationalCurrencyMagnitude",
    maximumFractionDigits: 2,
  },
  {
    id: "realGdp",
    canvasId: "realGdpChart",
    chartCardId: "realGdpChartCard",
    overlayId: "realGdpOverlay",
    statusId: "realGdpStatus",
    ...weoCurrentPrices,
    indicatorCode: "NGDP_R",
    titleTemplate: "Real GDP",
    usesCountryCurrency: true,
    valueScaleMode: "nationalCurrencyMagnitude",
    maximumFractionDigits: 2,
  },
  {
    id: "gdpGrowth",
    canvasId: "gdpGrowthChart",
    chartCardId: "gdpGrowthChartCard",
    overlayId: "gdpGrowthOverlay",
    statusId: "gdpGrowthStatus",
    ...weoCurrentPrices,
    indicatorCode: "NGDP_RPCH",
    titleTemplate: "Real GDP Growth Rate",
    suffix: "%",
    suffixSpacing: "",
    maximumFractionDigits: 1,
  },
  {
    id: "inflationRate",
    canvasId: "inflationRateChart",
    chartCardId: "inflationRateChartCard",
    overlayId: "inflationRateOverlay",
    statusId: "inflationRateStatus",
    ...weoCurrentPrices,
    indicatorCode: "PCPIPCH",
    titleTemplate: "Inflation Rate",
    suffix: "%",
    suffixSpacing: "",
    maximumFractionDigits: 1,
  },
  {
    id: "population",
    canvasId: "populationChart",
    chartCardId: "populationChartCard",
    overlayId: "populationOverlay",
    statusId: "populationStatus",
    ...weoCurrentPrices,
    indicatorCode: "LP",
    titleTemplate: "Population",
    valueScaleMode: "populationMagnitude",
    maximumFractionDigits: 1,
  },
  {
    id: "employment",
    canvasId: "employmentChart",
    chartCardId: "employmentChartCard",
    overlayId: "employmentOverlay",
    statusId: "employmentStatus",
    ...weoCurrentPrices,
    indicatorCode: "LE",
    titleTemplate: "Employment",
    valueScaleMode: "populationMagnitude",
    maximumFractionDigits: 1,
  },
  {
    id: "unemploymentRate",
    canvasId: "unemploymentRateChart",
    chartCardId: "unemploymentRateChartCard",
    overlayId: "unemploymentRateOverlay",
    statusId: "unemploymentRateStatus",
    ...weoCurrentPrices,
    indicatorCode: "LUR",
    titleTemplate: "Unemployment Rate",
    suffix: "%",
    suffixSpacing: "",
    maximumFractionDigits: 1,
  },
  {
    id: "lifeExpectancy",
    canvasId: "lifeExpectancyChart",
    chartCardId: "lifeExpectancyChartCard",
    overlayId: "lifeExpectancyOverlay",
    statusId: "lifeExpectancyStatus",
    ...worldBankPopulation,
    indicatorCode: "SP.DYN.LE00.IN",
    titleTemplate: "Life Expectancy",
    tooltipUnit: "years",
    maximumFractionDigits: 1,
  },
  {
    id: "fertilityRate",
    canvasId: "fertilityRateChart",
    chartCardId: "fertilityRateChartCard",
    overlayId: "fertilityRateOverlay",
    statusId: "fertilityRateStatus",
    ...worldBankPopulation,
    indicatorCode: "SP.DYN.TFRT.IN",
    titleTemplate: "Fertility Rate",
    maximumFractionDigits: 2,
  },
  {
    id: "gdpNationalPerCapita",
    canvasId: "gdpNationalPerCapitaChart",
    chartCardId: "gdpNationalPerCapitaChartCard",
    overlayId: "gdpNationalPerCapitaOverlay",
    statusId: "gdpNationalPerCapitaStatus",
    ...weoCurrentPrices,
    indicatorCode: "NGDPPC",
    titleTemplate: "Nominal GDP per capita",
    usesCountryCurrency: true,
    valueScale: 1,
    maximumFractionDigits: 0,
  },
  {
    id: "realGdpPerCapita",
    canvasId: "realGdpPerCapitaChart",
    chartCardId: "realGdpPerCapitaChartCard",
    overlayId: "realGdpPerCapitaOverlay",
    statusId: "realGdpPerCapitaStatus",
    ...weoCurrentPrices,
    indicatorCode: "NGDPRPC",
    titleTemplate: "Real GDP per capita",
    usesCountryCurrency: true,
    valueScale: 1,
    maximumFractionDigits: 0,
  },
  {
    id: "ppp",
    canvasId: "pppChart",
    chartCardId: "pppChartCard",
    overlayId: "pppOverlay",
    statusId: "pppStatus",
    ...weoCurrentPrices,
    indicatorCode: "PPPGDP",
    titleTemplate: "PPP GDP",
    currencyCode: "INT$",
    tooltipPrefix: "$",
    valueScaleMode: "internationalDollarMagnitude",
    maximumFractionDigits: 2,
  },
  {
    id: "pppPerCapita",
    canvasId: "pppPerCapitaChart",
    chartCardId: "pppPerCapitaChartCard",
    overlayId: "pppPerCapitaOverlay",
    statusId: "pppPerCapitaStatus",
    ...weoCurrentPrices,
    indicatorCode: "PPPPC",
    titleTemplate: "PPP GDP per capita",
    currencyCode: "INT$",
    tickPrefix: "$",
    tooltipPrefix: "$",
    tooltipUnit: "",
    maximumFractionDigits: 0,
  },
  {
    id: "currentAccountBalance",
    canvasId: "currentAccountBalanceChart",
    chartCardId: "currentAccountBalanceChartCard",
    overlayId: "currentAccountBalanceOverlay",
    statusId: "currentAccountBalanceStatus",
    ...weoCurrentPrices,
    indicatorCode: "BCA",
    titleTemplate: "Current Account Balance",
    currencyCode: "USD",
    tooltipPrefix: "$",
    valueScaleMode: "gdpMagnitude",
    maximumFractionDigits: 2,
  },
  {
    id: "currentAccountBalancePercentGdp",
    canvasId: "currentAccountBalancePercentGdpChart",
    chartCardId: "currentAccountBalancePercentGdpChartCard",
    overlayId: "currentAccountBalancePercentGdpOverlay",
    statusId: "currentAccountBalancePercentGdpStatus",
    ...weoCurrentPrices,
    indicatorCode: "BCA_NGDPD",
    titleTemplate: "Current Account Balance Percent of GDP",
    suffix: "%",
    suffixSpacing: "",
    maximumFractionDigits: 1,
  },
  {
    id: "goodsExports",
    canvasId: "goodsExportsChart",
    chartCardId: "goodsExportsChartCard",
    overlayId: "goodsExportsOverlay",
    statusId: "goodsExportsStatus",
    ...unctadGoodsTrade,
    indicatorCode: "GOODS_EXPORTS",
    titleTemplate: "Goods Exports",
    currencyCode: "USD",
    tooltipPrefix: "$",
    valueScaleMode: "usdMillionsMagnitude",
    maximumFractionDigits: 2,
  },
  {
    id: "goodsImports",
    canvasId: "goodsImportsChart",
    chartCardId: "goodsImportsChartCard",
    overlayId: "goodsImportsOverlay",
    statusId: "goodsImportsStatus",
    ...unctadGoodsTrade,
    indicatorCode: "GOODS_IMPORTS",
    titleTemplate: "Goods Imports",
    currencyCode: "USD",
    tooltipPrefix: "$",
    valueScaleMode: "usdMillionsMagnitude",
    maximumFractionDigits: 2,
  },
  {
    id: "goodsTradeBalance",
    canvasId: "goodsTradeBalanceChart",
    chartCardId: "goodsTradeBalanceChartCard",
    overlayId: "goodsTradeBalanceOverlay",
    statusId: "goodsTradeBalanceStatus",
    ...unctadGoodsTrade,
    indicatorCode: "GOODS_TRADE_BALANCE",
    titleTemplate: "Goods Trade Balance",
    currencyCode: "USD",
    tooltipPrefix: "$",
    valueScaleMode: "usdMillionsMagnitude",
    maximumFractionDigits: 2,
  },
  {
    id: "governmentGrossDebt",
    canvasId: "governmentGrossDebtChart",
    chartCardId: "governmentGrossDebtChartCard",
    overlayId: "governmentGrossDebtOverlay",
    statusId: "governmentGrossDebtStatus",
    ...weoCurrentPrices,
    indicatorCode: "GGXWDG_NGDP",
    titleTemplate: "Government Gross Debt",
    suffix: "%",
    suffixSpacing: "",
    maximumFractionDigits: 1,
  },
  {
    id: "governmentNetDebt",
    canvasId: "governmentNetDebtChart",
    chartCardId: "governmentNetDebtChartCard",
    overlayId: "governmentNetDebtOverlay",
    statusId: "governmentNetDebtStatus",
    ...weoCurrentPrices,
    indicatorCode: "GGXWDN_NGDP",
    titleTemplate: "Government Net Debt",
    suffix: "%",
    suffixSpacing: "",
    maximumFractionDigits: 1,
  },
  {
    id: "fiscalBalance",
    canvasId: "fiscalBalanceChart",
    chartCardId: "fiscalBalanceChartCard",
    overlayId: "fiscalBalanceOverlay",
    statusId: "fiscalBalanceStatus",
    ...weoCurrentPrices,
    indicatorCode: "GGXCNL_NGDP",
    titleTemplate: "Fiscal Balance",
    suffix: "%",
    suffixSpacing: "",
    maximumFractionDigits: 1,
  },
  {
    id: "primaryFiscalBalance",
    canvasId: "primaryFiscalBalanceChart",
    chartCardId: "primaryFiscalBalanceChartCard",
    overlayId: "primaryFiscalBalanceOverlay",
    statusId: "primaryFiscalBalanceStatus",
    ...weoCurrentPrices,
    indicatorCode: "GGXONLB_NGDP",
    titleTemplate: "Primary Fiscal Balance",
    suffix: "%",
    suffixSpacing: "",
    maximumFractionDigits: 1,
  },
  {
    id: "governmentRevenue",
    canvasId: "governmentRevenueChart",
    chartCardId: "governmentRevenueChartCard",
    overlayId: "governmentRevenueOverlay",
    statusId: "governmentRevenueStatus",
    ...weoCurrentPrices,
    indicatorCode: "GGR_NGDP",
    titleTemplate: "Government Revenue",
    suffix: "%",
    suffixSpacing: "",
    maximumFractionDigits: 1,
  },
  {
    id: "governmentExpenditure",
    canvasId: "governmentExpenditureChart",
    chartCardId: "governmentExpenditureChartCard",
    overlayId: "governmentExpenditureOverlay",
    statusId: "governmentExpenditureStatus",
    ...weoCurrentPrices,
    indicatorCode: "GGX_NGDP",
    titleTemplate: "Government Expenditure",
    suffix: "%",
    suffixSpacing: "",
    maximumFractionDigits: 1,
  },
  {
    id: "totalReservesIncludingGold",
    canvasId: "totalReservesIncludingGoldChart",
    chartCardId: "totalReservesIncludingGoldChartCard",
    overlayId: "totalReservesIncludingGoldOverlay",
    statusId: "totalReservesIncludingGoldStatus",
    ...worldBankWdi,
    indicatorCode: "FI.RES.TOTL.CD",
    titleTemplate: "Total Reserves Including Gold",
    currencyCode: "USD",
    tooltipPrefix: "$",
    valueScaleMode: "usdMagnitude",
    maximumFractionDigits: 2,
  },
  {
    id: "agriculturalLandPercentOfLandArea",
    canvasId: "agriculturalLandPercentOfLandAreaChart",
    chartCardId: "agriculturalLandPercentOfLandAreaChartCard",
    overlayId: "agriculturalLandPercentOfLandAreaOverlay",
    statusId: "agriculturalLandPercentOfLandAreaStatus",
    ...worldBankEnvironment,
    indicatorCode: "AG.LND.AGRI.ZS",
    titleTemplate: "Agricultural Land Percent of Land Area",
    suffix: "%",
    suffixSpacing: "",
    maximumFractionDigits: 1,
  },
  {
    id: "forestAreaPercentOfLandArea",
    canvasId: "forestAreaPercentOfLandAreaChart",
    chartCardId: "forestAreaPercentOfLandAreaChartCard",
    overlayId: "forestAreaPercentOfLandAreaOverlay",
    statusId: "forestAreaPercentOfLandAreaStatus",
    ...worldBankEnvironment,
    indicatorCode: "AG.LND.FRST.ZS",
    titleTemplate: "Forest Area Percent of Land Area",
    suffix: "%",
    suffixSpacing: "",
    maximumFractionDigits: 1,
  },
];
