export const countryCategories = [
  { id: "OECD", label: "OECD" },
  { id: "EU", label: "EU" },
  { id: "AU", label: "AU" },
  { id: "ASEAN", label: "ASEAN" },
  { id: "G20", label: "G20" },
  { id: "G7", label: "G7" },
  { id: "BRICS", label: "BRICS" },
  { id: "GCC", label: "GCC" },
];

export const countryRegions = [
  { id: "Asia", label: "Asia" },
  { id: "Europe", label: "Europe" },
  { id: "North America", label: "North America" },
  { id: "South America", label: "South America" },
  { id: "Africa", label: "Africa" },
  { id: "Oceania", label: "Oceania" },
];

export const countries = [
  { code: "WEOWORLD", name: "World", slug: "world", region: "", categories: [], includeInRankings: false },
  { code: "USA", name: "United States", slug: "united-states", region: "North America", categories: ["G20", "G7", "OECD"] },
  { code: "JPN", name: "Japan", slug: "japan", region: "Asia", categories: ["G20", "G7", "OECD"] },
  { code: "CHN", name: "China", slug: "china", region: "Asia", categories: ["G20", "BRICS"] },
  { code: "TWN", name: "Taiwan", slug: "taiwan", region: "Asia", categories: [] },
  { code: "HKG", name: "Hong Kong", slug: "hong-kong", region: "Asia", categories: [] },
  { code: "MAC", name: "Macao", slug: "macao", region: "Asia", categories: [] },
  { code: "DEU", name: "Germany", slug: "germany", region: "Europe", categories: ["G20", "EU", "G7", "OECD"] },
  { code: "FRA", name: "France", slug: "france", region: "Europe", categories: ["G20", "EU", "G7", "OECD"] },
  { code: "GBR", name: "United Kingdom", slug: "united-kingdom", region: "Europe", categories: ["G20", "G7", "OECD"] },
  { code: "ITA", name: "Italy", slug: "italy", region: "Europe", categories: ["G20", "EU", "G7", "OECD"] },
  { code: "CAN", name: "Canada", slug: "canada", region: "North America", categories: ["G20", "G7", "OECD"] },
  { code: "AUS", name: "Australia", slug: "australia", region: "Oceania", categories: ["G20", "OECD"] },
  { code: "NZL", name: "New Zealand", slug: "new-zealand", region: "Oceania", categories: ["OECD"] },
  { code: "ASM", name: "American Samoa", slug: "american-samoa", region: "Oceania", categories: [] },
  { code: "COK", name: "Cook Islands", slug: "cook-islands", region: "Oceania", categories: [] },
  { code: "FJI", name: "Fiji", slug: "fiji", region: "Oceania", categories: [] },
  { code: "GUM", name: "Guam", slug: "guam", region: "Oceania", categories: [] },
  { code: "MNP", name: "Northern Mariana Islands", slug: "northern-mariana-islands", region: "Oceania", categories: [] },
  { code: "NCL", name: "New Caledonia", slug: "new-caledonia", region: "Oceania", categories: [] },
  { code: "NIU", name: "Niue", slug: "niue", region: "Oceania", categories: [] },
  { code: "PCN", name: "Pitcairn", slug: "pitcairn", region: "Oceania", categories: [] },
  { code: "PNG", name: "Papua New Guinea", slug: "papua-new-guinea", region: "Oceania", categories: [] },
  { code: "PYF", name: "French Polynesia", slug: "french-polynesia", region: "Oceania", categories: [] },
  { code: "SLB", name: "Solomon Islands", slug: "solomon-islands", region: "Oceania", categories: [] },
  { code: "TKL", name: "Tokelau", slug: "tokelau", region: "Oceania", categories: [] },
  { code: "VUT", name: "Vanuatu", slug: "vanuatu", region: "Oceania", categories: [] },
  { code: "FSM", name: "Federated States of Micronesia", slug: "federated-states-of-micronesia", region: "Oceania", categories: [] },
  { code: "KIR", name: "Kiribati", slug: "kiribati", region: "Oceania", categories: [] },
  { code: "MHL", name: "Marshall Islands", slug: "marshall-islands", region: "Oceania", categories: [] },
  { code: "NRU", name: "Nauru", slug: "nauru", region: "Oceania", categories: [] },
  { code: "PLW", name: "Palau", slug: "palau", region: "Oceania", categories: [] },
  { code: "WSM", name: "Samoa", slug: "samoa", region: "Oceania", categories: [] },
  { code: "TON", name: "Tonga", slug: "tonga", region: "Oceania", categories: [] },
  { code: "TUV", name: "Tuvalu", slug: "tuvalu", region: "Oceania", categories: [] },
  { code: "WLF", name: "Wallis and Futuna Islands", slug: "wallis-and-futuna-islands", region: "Oceania", categories: [] },
  { code: "KOR", name: "South Korea", slug: "south-korea", region: "Asia", categories: ["G20", "OECD"] },
  { code: "PRK", name: "North Korea", slug: "north-korea", region: "Asia", categories: [] },
  { code: "IDN", name: "Indonesia", slug: "indonesia", region: "Asia", categories: ["G20", "ASEAN", "BRICS"] },
  { code: "TUR", name: "Turkey", slug: "turkey", region: "Europe / Asia", categories: ["G20", "OECD"] },
  { code: "IND", name: "India", slug: "india", region: "Asia", categories: ["G20", "BRICS"] },
  { code: "LKA", name: "Sri Lanka", slug: "sri-lanka", region: "Asia", categories: [] },
  { code: "MDV", name: "Maldives", slug: "maldives", region: "Asia", categories: [] },
  { code: "BGD", name: "Bangladesh", slug: "bangladesh", region: "Asia", categories: [] },
  { code: "BTN", name: "Bhutan", slug: "bhutan", region: "Asia", categories: [] },
  { code: "NPL", name: "Nepal", slug: "nepal", region: "Asia", categories: [] },
  { code: "PAK", name: "Pakistan", slug: "pakistan", region: "Asia", categories: [] },
  { code: "AFG", name: "Afghanistan", slug: "afghanistan", region: "Asia", categories: [] },
  { code: "TJK", name: "Tajikistan", slug: "tajikistan", region: "Asia", categories: [] },
  { code: "KGZ", name: "Kyrgyzstan", slug: "kyrgyzstan", region: "Asia", categories: [] },
  { code: "TKM", name: "Turkmenistan", slug: "turkmenistan", region: "Asia", categories: [] },
  { code: "UZB", name: "Uzbekistan", slug: "uzbekistan", region: "Asia", categories: [] },
  { code: "KAZ", name: "Kazakhstan", slug: "kazakhstan", region: "Asia", categories: [] },
  { code: "MNG", name: "Mongolia", slug: "mongolia", region: "Asia", categories: [] },
  { code: "AZE", name: "Azerbaijan", slug: "azerbaijan", region: "Asia", categories: [] },
  { code: "GEO", name: "Georgia", slug: "georgia", region: "Asia", categories: [] },
  { code: "ARM", name: "Armenia", slug: "armenia", region: "Asia", categories: [] },
  { code: "SAU", name: "Saudi Arabia", slug: "saudi-arabia", region: "Asia", categories: ["G20", "BRICS", "GCC"] },
  { code: "IRN", name: "Iran", slug: "iran", region: "Asia", categories: ["BRICS"] },
  { code: "IRQ", name: "Iraq", slug: "iraq", region: "Asia", categories: [] },
  { code: "SYR", name: "Syria", slug: "syria", region: "Asia", categories: [] },
  { code: "LBN", name: "Lebanon", slug: "lebanon", region: "Asia", categories: [] },
  { code: "JOR", name: "Jordan", slug: "jordan", region: "Asia", categories: [] },
  { code: "KWT", name: "Kuwait", slug: "kuwait", region: "Asia", categories: ["GCC"] },
  { code: "BHR", name: "Bahrain", slug: "bahrain", region: "Asia", categories: ["GCC"] },
  { code: "QAT", name: "Qatar", slug: "qatar", region: "Asia", categories: ["GCC"] },
  { code: "ARE", name: "United Arab Emirates", slug: "united-arab-emirates", region: "Asia", categories: ["BRICS", "GCC"] },
  { code: "OMN", name: "Oman", slug: "oman", region: "Asia", categories: ["GCC"] },
  { code: "YEM", name: "Yemen", slug: "yemen", region: "Asia", categories: [] },
  { code: "ARG", name: "Argentina", slug: "argentina", region: "South America", categories: ["G20"] },
  { code: "BRA", name: "Brazil", slug: "brazil", region: "South America", categories: ["G20", "BRICS"] },
  { code: "MEX", name: "Mexico", slug: "mexico", region: "North America", categories: ["G20", "OECD"] },
  { code: "ABW", name: "Aruba", slug: "aruba", region: "North America", categories: [] },
  { code: "AIA", name: "Anguilla", slug: "anguilla", region: "North America", categories: [] },
  { code: "BMU", name: "Bermuda", slug: "bermuda", region: "North America", categories: [] },
  { code: "GTM", name: "Guatemala", slug: "guatemala", region: "North America", categories: [] },
  { code: "BLZ", name: "Belize", slug: "belize", region: "North America", categories: [] },
  { code: "SLV", name: "El Salvador", slug: "el-salvador", region: "North America", categories: [] },
  { code: "HND", name: "Honduras", slug: "honduras", region: "North America", categories: [] },
  { code: "NIC", name: "Nicaragua", slug: "nicaragua", region: "North America", categories: [] },
  { code: "PAN", name: "Panama", slug: "panama", region: "North America", categories: [] },
  { code: "BHS", name: "Bahamas", slug: "bahamas", region: "North America", categories: [] },
  { code: "CUB", name: "Cuba", slug: "cuba", region: "North America", categories: [] },
  { code: "JAM", name: "Jamaica", slug: "jamaica", region: "North America", categories: [] },
  { code: "HTI", name: "Haiti", slug: "haiti", region: "North America", categories: [] },
  { code: "DOM", name: "Dominican Republic", slug: "dominican-republic", region: "North America", categories: [] },
  { code: "ATG", name: "Antigua and Barbuda", slug: "antigua-and-barbuda", region: "North America", categories: [] },
  { code: "KNA", name: "Saint Kitts and Nevis", slug: "saint-kitts-and-nevis", region: "North America", categories: [] },
  { code: "DMA", name: "Dominica", slug: "dominica", region: "North America", categories: [] },
  { code: "LCA", name: "Saint Lucia", slug: "saint-lucia", region: "North America", categories: [] },
  { code: "BRB", name: "Barbados", slug: "barbados", region: "North America", categories: [] },
  { code: "VCT", name: "Saint Vincent and the Grenadines", slug: "saint-vincent-and-the-grenadines", region: "North America", categories: [] },
  { code: "GRD", name: "Grenada", slug: "grenada", region: "North America", categories: [] },
  { code: "TTO", name: "Trinidad and Tobago", slug: "trinidad-and-tobago", region: "North America", categories: [] },
  { code: "CYM", name: "Cayman Islands", slug: "cayman-islands", region: "North America", categories: [] },
  { code: "CUW", name: "Curaçao", slug: "curacao", region: "North America", categories: [] },
  { code: "GLP", name: "Guadeloupe", slug: "guadeloupe", region: "North America", categories: [] },
  { code: "GRL", name: "Greenland", slug: "greenland", region: "North America", categories: [] },
  { code: "MAF", name: "Saint Martin", slug: "saint-martin", region: "North America", categories: [] },
  { code: "MSR", name: "Montserrat", slug: "montserrat", region: "North America", categories: [] },
  { code: "MTQ", name: "Martinique", slug: "martinique", region: "North America", categories: [] },
  { code: "PRI", name: "Puerto Rico", slug: "puerto-rico", region: "North America", categories: [] },
  { code: "SPM", name: "Saint Pierre and Miquelon", slug: "saint-pierre-and-miquelon", region: "North America", categories: [] },
  { code: "SXM", name: "Sint Maarten", slug: "sint-maarten", region: "North America", categories: [] },
  { code: "TCA", name: "Turks and Caicos Islands", slug: "turks-and-caicos-islands", region: "North America", categories: [] },
  { code: "VGB", name: "British Virgin Islands", slug: "british-virgin-islands", region: "North America", categories: [] },
  { code: "VIR", name: "United States Virgin Islands", slug: "united-states-virgin-islands", region: "North America", categories: [] },
  { code: "VEN", name: "Venezuela", slug: "venezuela", region: "South America", categories: [] },
  { code: "FLK", name: "Falkland Islands", slug: "falkland-islands", region: "South America", categories: [] },
  { code: "GUF", name: "French Guiana", slug: "french-guiana", region: "South America", categories: [] },
  { code: "GUY", name: "Guyana", slug: "guyana", region: "South America", categories: [] },
  { code: "SUR", name: "Suriname", slug: "suriname", region: "South America", categories: [] },
  { code: "ECU", name: "Ecuador", slug: "ecuador", region: "South America", categories: [] },
  { code: "BOL", name: "Bolivia", slug: "bolivia", region: "South America", categories: [] },
  { code: "PRY", name: "Paraguay", slug: "paraguay", region: "South America", categories: [] },
  { code: "URY", name: "Uruguay", slug: "uruguay", region: "South America", categories: [] },
  { code: "PER", name: "Peru", slug: "peru", region: "South America", categories: [] },
  { code: "RUS", name: "Russia", slug: "russia", region: "Europe / Asia", categories: ["G20", "BRICS"] },
  { code: "ZAF", name: "South Africa", slug: "south-africa", region: "Africa", categories: ["G20", "AU", "BRICS"] },
  { code: "CHL", name: "Chile", slug: "chile", region: "South America", categories: ["OECD"] },
  { code: "COL", name: "Colombia", slug: "colombia", region: "South America", categories: ["OECD"] },
  { code: "CRI", name: "Costa Rica", slug: "costa-rica", region: "North America", categories: ["OECD"] },
  { code: "NOR", name: "Norway", slug: "norway", region: "Europe", categories: ["OECD"] },
  { code: "ISL", name: "Iceland", slug: "iceland", region: "Europe", categories: ["OECD"] },
  { code: "CHE", name: "Switzerland", slug: "switzerland", region: "Europe", categories: ["OECD"] },
  { code: "ISR", name: "Israel", slug: "israel", region: "Asia", categories: ["OECD"] },
  { code: "FRO", name: "Faroe Islands", slug: "faroe-islands", region: "Europe", categories: [] },
  { code: "GIB", name: "Gibraltar", slug: "gibraltar", region: "Europe", categories: [] },
  { code: "IMN", name: "Isle of Man", slug: "isle-of-man", region: "Europe", categories: [] },
  { code: "LIE", name: "Liechtenstein", slug: "liechtenstein", region: "Europe", categories: [] },
  { code: "VAT", name: "Vatican City", slug: "vatican-city", region: "Europe", categories: [] },
  { code: "SMR", name: "San Marino", slug: "san-marino", region: "Europe", categories: [] },
  { code: "AND", name: "Andorra", slug: "andorra", region: "Europe", categories: [] },
  { code: "MCO", name: "Monaco", slug: "monaco", region: "Europe", categories: [] },
  { code: "BLR", name: "Belarus", slug: "belarus", region: "Europe", categories: [] },
  { code: "BIH", name: "Bosnia and Herzegovina", slug: "bosnia-and-herzegovina", region: "Europe", categories: [] },
  { code: "SRB", name: "Serbia", slug: "serbia", region: "Europe", categories: [] },
  { code: "MNE", name: "Montenegro", slug: "montenegro", region: "Europe", categories: [] },
  { code: "UVK", name: "Kosovo", slug: "kosovo", region: "Europe", categories: [] },
  { code: "MKD", name: "North Macedonia", slug: "north-macedonia", region: "Europe", categories: [] },
  { code: "ALB", name: "Albania", slug: "albania", region: "Europe", categories: [] },
  { code: "MDA", name: "Moldova", slug: "moldova", region: "Europe", categories: [] },
  { code: "UKR", name: "Ukraine", slug: "ukraine", region: "Europe", categories: [] },
  { code: "AUT", name: "Austria", slug: "austria", region: "Europe", categories: ["EU", "OECD"] },
  { code: "BEL", name: "Belgium", slug: "belgium", region: "Europe", categories: ["EU", "OECD"] },
  { code: "BGR", name: "Bulgaria", slug: "bulgaria", region: "Europe", categories: ["EU"] },
  { code: "HRV", name: "Croatia", slug: "croatia", region: "Europe", categories: ["EU"] },
  { code: "CYP", name: "Cyprus", slug: "cyprus", region: "Europe", categories: ["EU"] },
  { code: "CZE", name: "Czech Republic", slug: "czech-republic", region: "Europe", categories: ["EU", "OECD"] },
  { code: "DNK", name: "Denmark", slug: "denmark", region: "Europe", categories: ["EU", "OECD"] },
  { code: "EST", name: "Estonia", slug: "estonia", region: "Europe", categories: ["EU", "OECD"] },
  { code: "FIN", name: "Finland", slug: "finland", region: "Europe", categories: ["EU", "OECD"] },
  { code: "GRC", name: "Greece", slug: "greece", region: "Europe", categories: ["EU", "OECD"] },
  { code: "HUN", name: "Hungary", slug: "hungary", region: "Europe", categories: ["EU", "OECD"] },
  { code: "IRL", name: "Ireland", slug: "ireland", region: "Europe", categories: ["EU", "OECD"] },
  { code: "LVA", name: "Latvia", slug: "latvia", region: "Europe", categories: ["EU", "OECD"] },
  { code: "LTU", name: "Lithuania", slug: "lithuania", region: "Europe", categories: ["EU", "OECD"] },
  { code: "LUX", name: "Luxembourg", slug: "luxembourg", region: "Europe", categories: ["EU", "OECD"] },
  { code: "MLT", name: "Malta", slug: "malta", region: "Europe", categories: ["EU"] },
  { code: "NLD", name: "Netherlands", slug: "netherlands", region: "Europe", categories: ["EU", "OECD"] },
  { code: "POL", name: "Poland", slug: "poland", region: "Europe", categories: ["EU", "OECD"] },
  { code: "PRT", name: "Portugal", slug: "portugal", region: "Europe", categories: ["EU", "OECD"] },
  { code: "ROU", name: "Romania", slug: "romania", region: "Europe", categories: ["EU"] },
  { code: "SVK", name: "Slovakia", slug: "slovakia", region: "Europe", categories: ["EU", "OECD"] },
  { code: "SVN", name: "Slovenia", slug: "slovenia", region: "Europe", categories: ["EU", "OECD"] },
  { code: "ESP", name: "Spain", slug: "spain", region: "Europe", categories: ["EU", "OECD"] },
  { code: "SWE", name: "Sweden", slug: "sweden", region: "Europe", categories: ["EU", "OECD"] },
  { code: "BRN", name: "Brunei", slug: "brunei", region: "Asia", categories: ["ASEAN"] },
  { code: "KHM", name: "Cambodia", slug: "cambodia", region: "Asia", categories: ["ASEAN"] },
  { code: "LAO", name: "Laos", slug: "laos", region: "Asia", categories: ["ASEAN"] },
  { code: "MYS", name: "Malaysia", slug: "malaysia", region: "Asia", categories: ["ASEAN"] },
  { code: "MMR", name: "Myanmar", slug: "myanmar", region: "Asia", categories: ["ASEAN"] },
  { code: "PHL", name: "Philippines", slug: "philippines", region: "Asia", categories: ["ASEAN"] },
  { code: "SGP", name: "Singapore", slug: "singapore", region: "Asia", categories: ["ASEAN"] },
  { code: "THA", name: "Thailand", slug: "thailand", region: "Asia", categories: ["ASEAN"] },
  { code: "TLS", name: "Timor-Leste", slug: "timor-leste", region: "Asia", categories: ["ASEAN"] },
  { code: "VNM", name: "Vietnam", slug: "vietnam", region: "Asia", categories: ["ASEAN"] },
  { code: "WBG", name: "West Bank and Gaza", slug: "west-bank-and-gaza", region: "Asia", categories: [] },
  { code: "DZA", name: "Algeria", slug: "algeria", region: "Africa", categories: ["AU"] },
  { code: "AGO", name: "Angola", slug: "angola", region: "Africa", categories: ["AU"] },
  { code: "BEN", name: "Benin", slug: "benin", region: "Africa", categories: ["AU"] },
  { code: "BWA", name: "Botswana", slug: "botswana", region: "Africa", categories: ["AU"] },
  { code: "BFA", name: "Burkina Faso", slug: "burkina-faso", region: "Africa", categories: ["AU"] },
  { code: "BDI", name: "Burundi", slug: "burundi", region: "Africa", categories: ["AU"] },
  { code: "CPV", name: "Cabo Verde", slug: "cabo-verde", region: "Africa", categories: ["AU"] },
  { code: "CMR", name: "Cameroon", slug: "cameroon", region: "Africa", categories: ["AU"] },
  { code: "CAF", name: "Central African Republic", slug: "central-african-republic", region: "Africa", categories: ["AU"] },
  { code: "TCD", name: "Chad", slug: "chad", region: "Africa", categories: ["AU"] },
  { code: "COM", name: "Comoros", slug: "comoros", region: "Africa", categories: ["AU"] },
  { code: "COG", name: "Congo, Republic of", slug: "congo-republic-of", region: "Africa", categories: ["AU"] },
  { code: "COD", name: "Congo, Democratic Republic of the", slug: "congo-democratic-republic-of-the", region: "Africa", categories: ["AU"] },
  { code: "CIV", name: "Côte d’Ivoire", slug: "cote-divoire", region: "Africa", categories: ["AU"] },
  { code: "DJI", name: "Djibouti", slug: "djibouti", region: "Africa", categories: ["AU"] },
  { code: "EGY", name: "Egypt", slug: "egypt", region: "Africa", categories: ["AU", "BRICS"] },
  { code: "GNQ", name: "Equatorial Guinea", slug: "equatorial-guinea", region: "Africa", categories: ["AU"] },
  { code: "ERI", name: "Eritrea", slug: "eritrea", region: "Africa", categories: ["AU"] },
  { code: "SWZ", name: "Eswatini", slug: "eswatini", region: "Africa", categories: ["AU"] },
  { code: "ETH", name: "Ethiopia", slug: "ethiopia", region: "Africa", categories: ["AU", "BRICS"] },
  { code: "GAB", name: "Gabon", slug: "gabon", region: "Africa", categories: ["AU"] },
  { code: "GMB", name: "Gambia", slug: "gambia", region: "Africa", categories: ["AU"] },
  { code: "GHA", name: "Ghana", slug: "ghana", region: "Africa", categories: ["AU"] },
  { code: "GIN", name: "Guinea", slug: "guinea", region: "Africa", categories: ["AU"] },
  { code: "GNB", name: "Guinea-Bissau", slug: "guinea-bissau", region: "Africa", categories: ["AU"] },
  { code: "KEN", name: "Kenya", slug: "kenya", region: "Africa", categories: ["AU"] },
  { code: "LSO", name: "Lesotho", slug: "lesotho", region: "Africa", categories: ["AU"] },
  { code: "LBR", name: "Liberia", slug: "liberia", region: "Africa", categories: ["AU"] },
  { code: "LBY", name: "Libya", slug: "libya", region: "Africa", categories: ["AU"] },
  { code: "MDG", name: "Madagascar", slug: "madagascar", region: "Africa", categories: ["AU"] },
  { code: "MWI", name: "Malawi", slug: "malawi", region: "Africa", categories: ["AU"] },
  { code: "MYT", name: "Mayotte", slug: "mayotte", region: "Africa", categories: [] },
  { code: "MLI", name: "Mali", slug: "mali", region: "Africa", categories: ["AU"] },
  { code: "MRT", name: "Mauritania", slug: "mauritania", region: "Africa", categories: ["AU"] },
  { code: "MUS", name: "Mauritius", slug: "mauritius", region: "Africa", categories: ["AU"] },
  { code: "MAR", name: "Morocco", slug: "morocco", region: "Africa", categories: ["AU"] },
  { code: "MOZ", name: "Mozambique", slug: "mozambique", region: "Africa", categories: ["AU"] },
  { code: "NAM", name: "Namibia", slug: "namibia", region: "Africa", categories: ["AU"] },
  { code: "NER", name: "Niger", slug: "niger", region: "Africa", categories: ["AU"] },
  { code: "NGA", name: "Nigeria", slug: "nigeria", region: "Africa", categories: ["AU"] },
  { code: "RWA", name: "Rwanda", slug: "rwanda", region: "Africa", categories: ["AU"] },
  { code: "REU", name: "Réunion", slug: "reunion", region: "Africa", categories: [] },
  { code: "SHN", name: "Saint Helena", slug: "saint-helena", region: "Africa", categories: [] },
  { code: "STP", name: "São Tomé and Príncipe", slug: "sao-tome-and-principe", region: "Africa", categories: ["AU"] },
  { code: "SEN", name: "Senegal", slug: "senegal", region: "Africa", categories: ["AU"] },
  { code: "SYC", name: "Seychelles", slug: "seychelles", region: "Africa", categories: ["AU"] },
  { code: "SLE", name: "Sierra Leone", slug: "sierra-leone", region: "Africa", categories: ["AU"] },
  { code: "SOM", name: "Somalia", slug: "somalia", region: "Africa", categories: ["AU"] },
  { code: "SSD", name: "South Sudan", slug: "south-sudan", region: "Africa", categories: ["AU"] },
  { code: "SDN", name: "Sudan", slug: "sudan", region: "Africa", categories: ["AU"] },
  { code: "TZA", name: "Tanzania", slug: "tanzania", region: "Africa", categories: ["AU"] },
  { code: "TGO", name: "Togo", slug: "togo", region: "Africa", categories: ["AU"] },
  { code: "TUN", name: "Tunisia", slug: "tunisia", region: "Africa", categories: ["AU"] },
  { code: "UGA", name: "Uganda", slug: "uganda", region: "Africa", categories: ["AU"] },
  { code: "ZMB", name: "Zambia", slug: "zambia", region: "Africa", categories: ["AU"] },
  { code: "ZWE", name: "Zimbabwe", slug: "zimbabwe", region: "Africa", categories: ["AU"] },
];
