export const countryCategories = [
  { id: "OECD", label: "OECD" },
  { id: "EU", label: "EU" },
  { id: "ASEAN", label: "ASEAN" },
  { id: "G20", label: "G20" },
  { id: "G7", label: "G7" },
  { id: "BRICS", label: "BRICS" },
  { id: "Eurozone", label: "Eurozone" },
];

export const countryRegions = [
  { id: "Asia", label: "Asia" },
  { id: "Europe", label: "Europe" },
  { id: "North America", label: "North America" },
  { id: "South America", label: "South America" },
  { id: "Africa", label: "Africa" },
  { id: "Oceania", label: "Oceania" },
];

// Country search also reads optional aliases arrays when they are added to a country entry.
export const countries = [
  { code: "G001", name: "World", slug: "world", externalIds: { weo: { countryId: "G001" }, unctad: { m49: "0000" }, worldBank: { countryId: "WLD" } }, region: "", categories: [], includeInRankings: false },
  { code: "USA", name: "United States", slug: "united-states", externalIds: { weo: { countryId: "USA" }, unctad: { m49: "840" }, worldBank: { countryId: "USA" } }, aliases: ["United States of America"], region: "North America", categories: ["G20", "G7", "OECD"] },
  { code: "JPN", name: "Japan", slug: "japan", externalIds: { weo: { countryId: "JPN" }, unctad: { m49: "392" }, worldBank: { countryId: "JPN" } }, region: "Asia", categories: ["G20", "G7", "OECD"] },
  { code: "CHN", name: "China", slug: "china", externalIds: { weo: { countryId: "CHN" }, unctad: { m49: "156" }, worldBank: { countryId: "CHN" } }, aliases: ["People's Republic of China", "PRC"], region: "Asia", categories: ["G20", "BRICS"] },
  { code: "TWN", name: "Taiwan", slug: "taiwan", externalIds: { weo: { countryId: "TWN" }, unctad: { m49: "158" } }, aliases: ["Republic of China", "ROC"], region: "Asia", categories: [] },
  { code: "HKG", name: "Hong Kong", slug: "hong-kong", externalIds: { weo: { countryId: "HKG" }, unctad: { m49: "344" }, worldBank: { countryId: "HKG" } }, aliases: ["Hong Kong Special Administrative Region of the People's Republic of China"], region: "Asia", categories: [] },
  { code: "MAC", name: "Macao", slug: "macao", externalIds: { weo: { countryId: "MAC" }, unctad: { m49: "446" }, worldBank: { countryId: "MAC" } }, aliases: ["Macao Special Administrative Region of the People's Republic of China", "Macau"], region: "Asia", categories: [] },
  { code: "DEU", name: "Germany", slug: "germany", externalIds: { weo: { countryId: "DEU" }, unctad: { m49: "276" }, worldBank: { countryId: "DEU" } }, aliases: ["Federal Republic of Germany"], region: "Europe", categories: ["G20", "EU", "Eurozone", "G7", "OECD"] },
  { code: "FRA", name: "France", slug: "france", externalIds: { weo: { countryId: "FRA" }, unctad: { m49: "250" }, worldBank: { countryId: "FRA" } }, aliases: ["French Republic"], region: "Europe", categories: ["G20", "EU", "Eurozone", "G7", "OECD"] },
  { code: "GBR", name: "United Kingdom", slug: "united-kingdom", externalIds: { weo: { countryId: "GBR" }, unctad: { m49: "826" }, worldBank: { countryId: "GBR" } }, aliases: ["United Kingdom of Great Britain and Northern Ireland", "UK"], region: "Europe", categories: ["G20", "G7", "OECD"] },
  { code: "ITA", name: "Italy", slug: "italy", externalIds: { weo: { countryId: "ITA" }, unctad: { m49: "380" }, worldBank: { countryId: "ITA" } }, aliases: ["Italian Republic"], region: "Europe", categories: ["G20", "EU", "Eurozone", "G7", "OECD"] },
  { code: "CAN", name: "Canada", slug: "canada", externalIds: { weo: { countryId: "CAN" }, unctad: { m49: "124" }, worldBank: { countryId: "CAN" } }, region: "North America", categories: ["G20", "G7", "OECD"] },
  { code: "AUS", name: "Australia", slug: "australia", externalIds: { weo: { countryId: "AUS" }, unctad: { m49: "036" }, worldBank: { countryId: "AUS" } }, aliases: ["Commonwealth of Australia"], region: "Oceania", categories: ["G20", "OECD"] },
  { code: "NZL", name: "New Zealand", slug: "new-zealand", externalIds: { weo: { countryId: "NZL" }, unctad: { m49: "554" }, worldBank: { countryId: "NZL" } }, region: "Oceania", categories: ["OECD"] },
  { code: "ASM", name: "American Samoa", slug: "american-samoa", externalIds: { unctad: { m49: "016" }, worldBank: { countryId: "ASM" } }, region: "Oceania", categories: [] },
  { code: "COK", name: "Cook Islands", slug: "cook-islands", externalIds: { unctad: { m49: "184" } }, region: "Oceania", categories: [] },
  { code: "FJI", name: "Fiji", slug: "fiji", externalIds: { weo: { countryId: "FJI" }, unctad: { m49: "242" }, worldBank: { countryId: "FJI" } }, aliases: ["Republic of Fiji"], region: "Oceania", categories: [] },
  { code: "GUM", name: "Guam", slug: "guam", externalIds: { unctad: { m49: "316" }, worldBank: { countryId: "GUM" } }, region: "Oceania", categories: [] },
  { code: "MNP", name: "Northern Mariana Islands", slug: "northern-mariana-islands", externalIds: { unctad: { m49: "580" }, worldBank: { countryId: "MNP" } }, aliases: ["Commonwealth of the Northern Mariana Islands", "CNMI"], region: "Oceania", categories: [] },
  { code: "NCL", name: "New Caledonia", slug: "new-caledonia", externalIds: { unctad: { m49: "540" }, worldBank: { countryId: "NCL" } }, region: "Oceania", categories: [] },
  { code: "NIU", name: "Niue", slug: "niue", externalIds: { unctad: { m49: "570" } }, region: "Oceania", categories: [] },
  { code: "PCN", name: "Pitcairn", slug: "pitcairn", aliases: ["Pitcairn, Henderson, Ducie and Oeno Islands"], region: "Oceania", categories: [] },
  { code: "PNG", name: "Papua New Guinea", slug: "papua-new-guinea", externalIds: { weo: { countryId: "PNG" }, unctad: { m49: "598" }, worldBank: { countryId: "PNG" } }, aliases: ["Independent State of Papua New Guinea"], region: "Oceania", categories: [] },
  { code: "PYF", name: "French Polynesia", slug: "french-polynesia", externalIds: { unctad: { m49: "258" }, worldBank: { countryId: "PYF" } }, region: "Oceania", categories: [] },
  { code: "SLB", name: "Solomon Islands", slug: "solomon-islands", externalIds: { weo: { countryId: "SLB" }, unctad: { m49: "090" }, worldBank: { countryId: "SLB" } }, region: "Oceania", categories: [] },
  { code: "TKL", name: "Tokelau", slug: "tokelau", externalIds: { unctad: { m49: "772" } }, region: "Oceania", categories: [] },
  { code: "VUT", name: "Vanuatu", slug: "vanuatu", externalIds: { weo: { countryId: "VUT" }, unctad: { m49: "548" }, worldBank: { countryId: "VUT" } }, aliases: ["Republic of Vanuatu"], region: "Oceania", categories: [] },
  { code: "FSM", name: "Federated States of Micronesia", slug: "federated-states-of-micronesia", externalIds: { weo: { countryId: "FSM" }, unctad: { m49: "583" }, worldBank: { countryId: "FSM" } }, region: "Oceania", categories: [] },
  { code: "KIR", name: "Kiribati", slug: "kiribati", externalIds: { weo: { countryId: "KIR" }, unctad: { m49: "296" }, worldBank: { countryId: "KIR" } }, aliases: ["Republic of Kiribati"], region: "Oceania", categories: [] },
  { code: "MHL", name: "Marshall Islands", slug: "marshall-islands", externalIds: { weo: { countryId: "MHL" }, unctad: { m49: "584" }, worldBank: { countryId: "MHL" } }, region: "Oceania", categories: [] },
  { code: "NRU", name: "Nauru", slug: "nauru", externalIds: { weo: { countryId: "NRU" }, unctad: { m49: "520" }, worldBank: { countryId: "NRU" } }, aliases: ["Republic of Nauru"], region: "Oceania", categories: [] },
  { code: "PLW", name: "Palau", slug: "palau", externalIds: { weo: { countryId: "PLW" }, unctad: { m49: "585" }, worldBank: { countryId: "PLW" } }, aliases: ["Republic of Palau"], region: "Oceania", categories: [] },
  { code: "WSM", name: "Samoa", slug: "samoa", externalIds: { weo: { countryId: "WSM" }, unctad: { m49: "882" }, worldBank: { countryId: "WSM" } }, aliases: ["Independent State of Samoa"], region: "Oceania", categories: [] },
  { code: "TON", name: "Tonga", slug: "tonga", externalIds: { weo: { countryId: "TON" }, unctad: { m49: "776" }, worldBank: { countryId: "TON" } }, aliases: ["Kingdom of Tonga"], region: "Oceania", categories: [] },
  { code: "TUV", name: "Tuvalu", slug: "tuvalu", externalIds: { weo: { countryId: "TUV" }, unctad: { m49: "798" }, worldBank: { countryId: "TUV" } }, region: "Oceania", categories: [] },
  { code: "WLF", name: "Wallis and Futuna", slug: "wallis-and-futuna", externalIds: { unctad: { m49: "876" } }, aliases: ["Territory of the Wallis and Futuna Islands"], region: "Oceania", categories: [] },
  { code: "KOR", name: "South Korea", slug: "south-korea", externalIds: { weo: { countryId: "KOR" }, unctad: { m49: "410" }, worldBank: { countryId: "KOR" } }, aliases: ["Republic of Korea", "ROK"], region: "Asia", categories: ["G20", "OECD"] },
  { code: "PRK", name: "North Korea", slug: "north-korea", externalIds: { unctad: { m49: "408" }, worldBank: { countryId: "PRK" } }, aliases: ["Democratic People's Republic of Korea", "DPRK"], region: "Asia", categories: [] },
  { code: "IDN", name: "Indonesia", slug: "indonesia", externalIds: { weo: { countryId: "IDN" }, unctad: { m49: "360" }, worldBank: { countryId: "IDN" } }, aliases: ["Republic of Indonesia"], region: "Asia", categories: ["G20", "ASEAN", "BRICS"] },
  { code: "TUR", name: "Türkiye", slug: "turkiye", externalIds: { weo: { countryId: "TUR" }, unctad: { m49: "792" }, worldBank: { countryId: "TUR" } }, aliases: ["Turkey"], region: "Europe / Asia", categories: ["G20", "OECD"] },
  { code: "IND", name: "India", slug: "india", externalIds: { weo: { countryId: "IND" }, unctad: { m49: "356" }, worldBank: { countryId: "IND" } }, region: "Asia", categories: ["G20", "BRICS"] },
  { code: "LKA", name: "Sri Lanka", slug: "sri-lanka", externalIds: { weo: { countryId: "LKA" }, unctad: { m49: "144" }, worldBank: { countryId: "LKA" } }, aliases: ["Ceylon"], region: "Asia", categories: [] },
  { code: "MDV", name: "Maldives", slug: "maldives", externalIds: { weo: { countryId: "MDV" }, unctad: { m49: "462" }, worldBank: { countryId: "MDV" } }, region: "Asia", categories: [] },
  { code: "BGD", name: "Bangladesh", slug: "bangladesh", externalIds: { weo: { countryId: "BGD" }, unctad: { m49: "050" }, worldBank: { countryId: "BGD" } }, region: "Asia", categories: [] },
  { code: "BTN", name: "Bhutan", slug: "bhutan", externalIds: { weo: { countryId: "BTN" }, unctad: { m49: "064" }, worldBank: { countryId: "BTN" } }, region: "Asia", categories: [] },
  { code: "NPL", name: "Nepal", slug: "nepal", externalIds: { weo: { countryId: "NPL" }, unctad: { m49: "524" }, worldBank: { countryId: "NPL" } }, region: "Asia", categories: [] },
  { code: "PAK", name: "Pakistan", slug: "pakistan", externalIds: { weo: { countryId: "PAK" }, unctad: { m49: "586" }, worldBank: { countryId: "PAK" } }, region: "Asia", categories: [] },
  { code: "AFG", name: "Afghanistan", slug: "afghanistan", externalIds: { weo: { countryId: "AFG" }, unctad: { m49: "004" }, worldBank: { countryId: "AFG" } }, region: "Asia", categories: [] },
  { code: "TJK", name: "Tajikistan", slug: "tajikistan", externalIds: { weo: { countryId: "TJK" }, unctad: { m49: "762" }, worldBank: { countryId: "TJK" } }, region: "Asia", categories: [] },
  { code: "KGZ", name: "Kyrgyzstan", slug: "kyrgyzstan", externalIds: { weo: { countryId: "KGZ" }, unctad: { m49: "417" }, worldBank: { countryId: "KGZ" } }, region: "Asia", categories: [] },
  { code: "TKM", name: "Turkmenistan", slug: "turkmenistan", externalIds: { weo: { countryId: "TKM" }, unctad: { m49: "795" }, worldBank: { countryId: "TKM" } }, region: "Asia", categories: [] },
  { code: "UZB", name: "Uzbekistan", slug: "uzbekistan", externalIds: { weo: { countryId: "UZB" }, unctad: { m49: "860" }, worldBank: { countryId: "UZB" } }, region: "Asia", categories: [] },
  { code: "KAZ", name: "Kazakhstan", slug: "kazakhstan", externalIds: { weo: { countryId: "KAZ" }, unctad: { m49: "398" }, worldBank: { countryId: "KAZ" } }, region: "Asia", categories: [] },
  { code: "MNG", name: "Mongolia", slug: "mongolia", externalIds: { weo: { countryId: "MNG" }, unctad: { m49: "496" }, worldBank: { countryId: "MNG" } }, region: "Asia", categories: [] },
  { code: "AZE", name: "Azerbaijan", slug: "azerbaijan", externalIds: { weo: { countryId: "AZE" }, unctad: { m49: "031" }, worldBank: { countryId: "AZE" } }, region: "Asia", categories: [] },
  { code: "GEO", name: "Georgia", slug: "georgia", externalIds: { weo: { countryId: "GEO" }, unctad: { m49: "268" }, worldBank: { countryId: "GEO" } }, region: "Asia", categories: [] },
  { code: "ARM", name: "Armenia", slug: "armenia", externalIds: { weo: { countryId: "ARM" }, unctad: { m49: "051" }, worldBank: { countryId: "ARM" } }, region: "Asia", categories: [] },
  { code: "SAU", name: "Saudi Arabia", slug: "saudi-arabia", externalIds: { weo: { countryId: "SAU" }, unctad: { m49: "682" }, worldBank: { countryId: "SAU" } }, region: "Asia", categories: ["G20", "BRICS", "GCC"] },
  { code: "IRN", name: "Iran", slug: "iran", externalIds: { weo: { countryId: "IRN" }, unctad: { m49: "364" }, worldBank: { countryId: "IRN" } }, aliases: ["Persia"], region: "Asia", categories: ["BRICS"] },
  { code: "IRQ", name: "Iraq", slug: "iraq", externalIds: { weo: { countryId: "IRQ" }, unctad: { m49: "368" }, worldBank: { countryId: "IRQ" } }, region: "Asia", categories: [] },
  { code: "SYR", name: "Syria", slug: "syria", externalIds: { weo: { countryId: "SYR" }, unctad: { m49: "760" }, worldBank: { countryId: "SYR" } }, region: "Asia", categories: [] },
  { code: "LBN", name: "Lebanon", slug: "lebanon", externalIds: { weo: { countryId: "LBN" }, unctad: { m49: "422" }, worldBank: { countryId: "LBN" } }, region: "Asia", categories: [] },
  { code: "JOR", name: "Jordan", slug: "jordan", externalIds: { weo: { countryId: "JOR" }, unctad: { m49: "400" }, worldBank: { countryId: "JOR" } }, region: "Asia", categories: [] },
  { code: "KWT", name: "Kuwait", slug: "kuwait", externalIds: { weo: { countryId: "KWT" }, unctad: { m49: "414" }, worldBank: { countryId: "KWT" } }, region: "Asia", categories: ["GCC"] },
  { code: "BHR", name: "Bahrain", slug: "bahrain", externalIds: { weo: { countryId: "BHR" }, unctad: { m49: "048" }, worldBank: { countryId: "BHR" } }, region: "Asia", categories: ["GCC"] },
  { code: "QAT", name: "Qatar", slug: "qatar", externalIds: { weo: { countryId: "QAT" }, unctad: { m49: "634" }, worldBank: { countryId: "QAT" } }, region: "Asia", categories: ["GCC"] },
  { code: "ARE", name: "United Arab Emirates", slug: "united-arab-emirates", externalIds: { weo: { countryId: "ARE" }, unctad: { m49: "784" }, worldBank: { countryId: "ARE" } }, aliases: ["UAE"], region: "Asia", categories: ["BRICS", "GCC"] },
  { code: "OMN", name: "Oman", slug: "oman", externalIds: { weo: { countryId: "OMN" }, unctad: { m49: "512" }, worldBank: { countryId: "OMN" } }, region: "Asia", categories: ["GCC"] },
  { code: "YEM", name: "Yemen", slug: "yemen", externalIds: { weo: { countryId: "YEM" }, unctad: { m49: "887" }, worldBank: { countryId: "YEM" } }, region: "Asia", categories: [] },
  { code: "ARG", name: "Argentina", slug: "argentina", externalIds: { weo: { countryId: "ARG" }, unctad: { m49: "032" }, worldBank: { countryId: "ARG" } }, region: "South America", categories: ["G20"] },
  { code: "BRA", name: "Brazil", slug: "brazil", externalIds: { weo: { countryId: "BRA" }, unctad: { m49: "076" }, worldBank: { countryId: "BRA" } }, region: "South America", categories: ["G20", "BRICS"] },
  { code: "MEX", name: "Mexico", slug: "mexico", externalIds: { weo: { countryId: "MEX" }, unctad: { m49: "484" }, worldBank: { countryId: "MEX" } }, region: "North America", categories: ["G20", "OECD"] },
  { code: "ABW", name: "Aruba", slug: "aruba", externalIds: { weo: { countryId: "ABW" }, unctad: { m49: "533" }, worldBank: { countryId: "ABW" } }, region: "North America", categories: [] },
  { code: "AIA", name: "Anguilla", slug: "anguilla", externalIds: { unctad: { m49: "660" } }, region: "North America", categories: [] },
  { code: "BMU", name: "Bermuda", slug: "bermuda", externalIds: { unctad: { m49: "060" }, worldBank: { countryId: "BMU" } }, region: "North America", categories: [] },
  { code: "GTM", name: "Guatemala", slug: "guatemala", externalIds: { weo: { countryId: "GTM" }, unctad: { m49: "320" }, worldBank: { countryId: "GTM" } }, region: "North America", categories: [] },
  { code: "BLZ", name: "Belize", slug: "belize", externalIds: { weo: { countryId: "BLZ" }, unctad: { m49: "084" }, worldBank: { countryId: "BLZ" } }, region: "North America", categories: [] },
  { code: "SLV", name: "El Salvador", slug: "el-salvador", externalIds: { weo: { countryId: "SLV" }, unctad: { m49: "222" }, worldBank: { countryId: "SLV" } }, region: "North America", categories: [] },
  { code: "HND", name: "Honduras", slug: "honduras", externalIds: { weo: { countryId: "HND" }, unctad: { m49: "340" }, worldBank: { countryId: "HND" } }, region: "North America", categories: [] },
  { code: "NIC", name: "Nicaragua", slug: "nicaragua", externalIds: { weo: { countryId: "NIC" }, unctad: { m49: "558" }, worldBank: { countryId: "NIC" } }, region: "North America", categories: [] },
  { code: "PAN", name: "Panama", slug: "panama", externalIds: { weo: { countryId: "PAN" }, unctad: { m49: "591" }, worldBank: { countryId: "PAN" } }, region: "North America", categories: [] },
  { code: "BHS", name: "Bahamas", slug: "bahamas", externalIds: { weo: { countryId: "BHS" }, unctad: { m49: "044" }, worldBank: { countryId: "BHS" } }, region: "North America", categories: [] },
  { code: "CUB", name: "Cuba", slug: "cuba", externalIds: { unctad: { m49: "192" }, worldBank: { countryId: "CUB" } }, region: "North America", categories: [] },
  { code: "JAM", name: "Jamaica", slug: "jamaica", externalIds: { weo: { countryId: "JAM" }, unctad: { m49: "388" }, worldBank: { countryId: "JAM" } }, region: "North America", categories: [] },
  { code: "HTI", name: "Haiti", slug: "haiti", externalIds: { weo: { countryId: "HTI" }, unctad: { m49: "332" }, worldBank: { countryId: "HTI" } }, region: "North America", categories: [] },
  { code: "DOM", name: "Dominican Republic", slug: "dominican-republic", externalIds: { weo: { countryId: "DOM" }, unctad: { m49: "214" }, worldBank: { countryId: "DOM" } }, region: "North America", categories: [] },
  { code: "ATG", name: "Antigua and Barbuda", slug: "antigua-and-barbuda", externalIds: { weo: { countryId: "ATG" }, unctad: { m49: "028" }, worldBank: { countryId: "ATG" } }, region: "North America", categories: [] },
  { code: "KNA", name: "Saint Kitts and Nevis", slug: "saint-kitts-and-nevis", externalIds: { weo: { countryId: "KNA" }, unctad: { m49: "659" }, worldBank: { countryId: "KNA" } }, region: "North America", categories: [] },
  { code: "DMA", name: "Dominica", slug: "dominica", externalIds: { weo: { countryId: "DMA" }, unctad: { m49: "212" }, worldBank: { countryId: "DMA" } }, region: "North America", categories: [] },
  { code: "LCA", name: "Saint Lucia", slug: "saint-lucia", externalIds: { weo: { countryId: "LCA" }, unctad: { m49: "662" }, worldBank: { countryId: "LCA" } }, region: "North America", categories: [] },
  { code: "BRB", name: "Barbados", slug: "barbados", externalIds: { weo: { countryId: "BRB" }, unctad: { m49: "052" }, worldBank: { countryId: "BRB" } }, region: "North America", categories: [] },
  { code: "VCT", name: "Saint Vincent and the Grenadines", slug: "saint-vincent-and-the-grenadines", externalIds: { weo: { countryId: "VCT" }, unctad: { m49: "670" }, worldBank: { countryId: "VCT" } }, region: "North America", categories: [] },
  { code: "GRD", name: "Grenada", slug: "grenada", externalIds: { weo: { countryId: "GRD" }, unctad: { m49: "308" }, worldBank: { countryId: "GRD" } }, region: "North America", categories: [] },
  { code: "TTO", name: "Trinidad and Tobago", slug: "trinidad-and-tobago", externalIds: { weo: { countryId: "TTO" }, unctad: { m49: "780" }, worldBank: { countryId: "TTO" } }, region: "North America", categories: [] },
  { code: "CYM", name: "Cayman Islands", slug: "cayman-islands", externalIds: { unctad: { m49: "136" }, worldBank: { countryId: "CYM" } }, region: "North America", categories: [] },
  { code: "CUW", name: "Curaçao", slug: "curacao", externalIds: { unctad: { m49: "531" }, worldBank: { countryId: "CUW" } }, region: "North America", categories: [] },
  { code: "GLP", name: "Guadeloupe", slug: "guadeloupe", externalIds: { unctad: { m49: "312" } }, region: "North America", categories: [] },
  { code: "GRL", name: "Greenland", slug: "greenland", externalIds: { unctad: { m49: "304" }, worldBank: { countryId: "GRL" } }, region: "North America", categories: [] },
  { code: "MAF", name: "Saint Martin", slug: "saint-martin", externalIds: { worldBank: { countryId: "MAF" } }, region: "North America", categories: [] },
  { code: "MSR", name: "Montserrat", slug: "montserrat", externalIds: { unctad: { m49: "500" } }, region: "North America", categories: [] },
  { code: "MTQ", name: "Martinique", slug: "martinique", externalIds: { unctad: { m49: "474" } }, region: "North America", categories: [] },
  { code: "PRI", name: "Puerto Rico", slug: "puerto-rico", externalIds: { weo: { countryId: "PRI" }, worldBank: { countryId: "PRI" } }, region: "North America", categories: [] },
  { code: "SPM", name: "Saint Pierre and Miquelon", slug: "saint-pierre-and-miquelon", externalIds: { unctad: { m49: "666" } }, region: "North America", categories: [] },
  { code: "SXM", name: "Sint Maarten", slug: "sint-maarten", externalIds: { unctad: { m49: "534" }, worldBank: { countryId: "SXM" } }, region: "North America", categories: [] },
  { code: "TCA", name: "Turks and Caicos Islands", slug: "turks-and-caicos-islands", externalIds: { unctad: { m49: "796" }, worldBank: { countryId: "TCA" } }, region: "North America", categories: [] },
  { code: "VGB", name: "British Virgin Islands", slug: "british-virgin-islands", externalIds: { unctad: { m49: "092" }, worldBank: { countryId: "VGB" } }, region: "North America", categories: [] },
  { code: "VIR", name: "U.S. Virgin Islands", slug: "us-virgin-islands", externalIds: { worldBank: { countryId: "VIR" } }, region: "North America", categories: [] },
  { code: "VEN", name: "Venezuela", slug: "venezuela", externalIds: { weo: { countryId: "VEN" }, unctad: { m49: "862" }, worldBank: { countryId: "VEN" } }, region: "South America", categories: [] },
  { code: "FLK", name: "Falkland Islands", slug: "falkland-islands", externalIds: { unctad: { m49: "238" } }, region: "South America", categories: [] },
  { code: "GUF", name: "French Guiana", slug: "french-guiana", externalIds: { unctad: { m49: "254" } }, region: "South America", categories: [] },
  { code: "GUY", name: "Guyana", slug: "guyana", externalIds: { weo: { countryId: "GUY" }, unctad: { m49: "328" }, worldBank: { countryId: "GUY" } }, region: "South America", categories: [] },
  { code: "SUR", name: "Suriname", slug: "suriname", externalIds: { weo: { countryId: "SUR" }, unctad: { m49: "740" }, worldBank: { countryId: "SUR" } }, region: "South America", categories: [] },
  { code: "ECU", name: "Ecuador", slug: "ecuador", externalIds: { weo: { countryId: "ECU" }, unctad: { m49: "218" }, worldBank: { countryId: "ECU" } }, region: "South America", categories: [] },
  { code: "BOL", name: "Bolivia", slug: "bolivia", externalIds: { weo: { countryId: "BOL" }, unctad: { m49: "068" }, worldBank: { countryId: "BOL" } }, region: "South America", categories: [] },
  { code: "PRY", name: "Paraguay", slug: "paraguay", externalIds: { weo: { countryId: "PRY" }, unctad: { m49: "600" }, worldBank: { countryId: "PRY" } }, region: "South America", categories: [] },
  { code: "URY", name: "Uruguay", slug: "uruguay", externalIds: { weo: { countryId: "URY" }, unctad: { m49: "858" }, worldBank: { countryId: "URY" } }, region: "South America", categories: [] },
  { code: "PER", name: "Peru", slug: "peru", externalIds: { weo: { countryId: "PER" }, unctad: { m49: "604" }, worldBank: { countryId: "PER" } }, region: "South America", categories: [] },
  { code: "RUS", name: "Russia", slug: "russia", externalIds: { weo: { countryId: "RUS" }, unctad: { m49: "643" }, worldBank: { countryId: "RUS" } }, region: "Europe / Asia", categories: ["G20", "BRICS"] },
  { code: "ZAF", name: "South Africa", slug: "south-africa", externalIds: { weo: { countryId: "ZAF" }, unctad: { m49: "710" }, worldBank: { countryId: "ZAF" } }, region: "Africa", categories: ["G20", "AU", "BRICS"] },
  { code: "CHL", name: "Chile", slug: "chile", externalIds: { weo: { countryId: "CHL" }, unctad: { m49: "152" }, worldBank: { countryId: "CHL" } }, region: "South America", categories: ["OECD"] },
  { code: "COL", name: "Colombia", slug: "colombia", externalIds: { weo: { countryId: "COL" }, unctad: { m49: "170" }, worldBank: { countryId: "COL" } }, region: "South America", categories: ["OECD"] },
  { code: "CRI", name: "Costa Rica", slug: "costa-rica", externalIds: { weo: { countryId: "CRI" }, unctad: { m49: "188" }, worldBank: { countryId: "CRI" } }, region: "North America", categories: ["OECD"] },
  { code: "NOR", name: "Norway", slug: "norway", externalIds: { weo: { countryId: "NOR" }, unctad: { m49: "578" }, worldBank: { countryId: "NOR" } }, region: "Europe", categories: ["OECD"] },
  { code: "ISL", name: "Iceland", slug: "iceland", externalIds: { weo: { countryId: "ISL" }, unctad: { m49: "352" }, worldBank: { countryId: "ISL" } }, region: "Europe", categories: ["OECD"] },
  { code: "CHE", name: "Switzerland", slug: "switzerland", externalIds: { weo: { countryId: "CHE" }, unctad: { m49: "756" }, worldBank: { countryId: "CHE" } }, region: "Europe", categories: ["OECD"] },
  { code: "ISR", name: "Israel", slug: "israel", externalIds: { weo: { countryId: "ISR" }, unctad: { m49: "376" }, worldBank: { countryId: "ISR" } }, region: "Asia", categories: ["OECD"] },
  { code: "FRO", name: "Faroe Islands", slug: "faroe-islands", externalIds: { unctad: { m49: "234" }, worldBank: { countryId: "FRO" } }, region: "Europe", categories: [] },
  { code: "GIB", name: "Gibraltar", slug: "gibraltar", externalIds: { unctad: { m49: "292" }, worldBank: { countryId: "GIB" } }, region: "Europe", categories: [] },
  { code: "IMN", name: "Isle of Man", slug: "isle-of-man", externalIds: { worldBank: { countryId: "IMN" } }, region: "Europe", categories: [] },
  { code: "LIE", name: "Liechtenstein", slug: "liechtenstein", externalIds: { weo: { countryId: "LIE" }, worldBank: { countryId: "LIE" } }, region: "Europe", categories: [] },
  { code: "VAT", name: "Vatican City", slug: "vatican-city", aliases: ["Holy See"], region: "Europe", categories: [] },
  { code: "SMR", name: "San Marino", slug: "san-marino", externalIds: { weo: { countryId: "SMR" }, worldBank: { countryId: "SMR" } }, region: "Europe", categories: [] },
  { code: "AND", name: "Andorra", slug: "andorra", externalIds: { weo: { countryId: "AND" }, unctad: { m49: "020" }, worldBank: { countryId: "AND" } }, region: "Europe", categories: [] },
  { code: "MCO", name: "Monaco", slug: "monaco", externalIds: { worldBank: { countryId: "MCO" } }, region: "Europe", categories: [] },
  { code: "BLR", name: "Belarus", slug: "belarus", externalIds: { weo: { countryId: "BLR" }, unctad: { m49: "112" }, worldBank: { countryId: "BLR" } }, region: "Europe", categories: [] },
  { code: "BIH", name: "Bosnia and Herzegovina", slug: "bosnia-and-herzegovina", externalIds: { weo: { countryId: "BIH" }, unctad: { m49: "070" }, worldBank: { countryId: "BIH" } }, region: "Europe", categories: [] },
  { code: "SRB", name: "Serbia", slug: "serbia", externalIds: { weo: { countryId: "SRB" }, unctad: { m49: "688" }, worldBank: { countryId: "SRB" } }, region: "Europe", categories: [] },
  { code: "MNE", name: "Montenegro", slug: "montenegro", externalIds: { weo: { countryId: "MNE" }, unctad: { m49: "499" }, worldBank: { countryId: "MNE" } }, region: "Europe", categories: [] },
  { code: "KOS", name: "Kosovo", slug: "kosovo", externalIds: { weo: { countryId: "KOS" }, worldBank: { countryId: "XKX" } }, region: "Europe", categories: [] },
  { code: "MKD", name: "North Macedonia", slug: "north-macedonia", externalIds: { weo: { countryId: "MKD" }, unctad: { m49: "807" }, worldBank: { countryId: "MKD" } }, region: "Europe", categories: [] },
  { code: "ALB", name: "Albania", slug: "albania", externalIds: { weo: { countryId: "ALB" }, unctad: { m49: "008" }, worldBank: { countryId: "ALB" } }, region: "Europe", categories: [] },
  { code: "MDA", name: "Moldova", slug: "moldova", externalIds: { weo: { countryId: "MDA" }, unctad: { m49: "498" }, worldBank: { countryId: "MDA" } }, region: "Europe", categories: [] },
  { code: "UKR", name: "Ukraine", slug: "ukraine", externalIds: { weo: { countryId: "UKR" }, unctad: { m49: "804" }, worldBank: { countryId: "UKR" } }, region: "Europe", categories: [] },
  { code: "AUT", name: "Austria", slug: "austria", externalIds: { weo: { countryId: "AUT" }, unctad: { m49: "040" }, worldBank: { countryId: "AUT" } }, region: "Europe", categories: ["EU", "Eurozone", "OECD"] },
  { code: "BEL", name: "Belgium", slug: "belgium", externalIds: { weo: { countryId: "BEL" }, unctad: { m49: "056" }, worldBank: { countryId: "BEL" } }, region: "Europe", categories: ["EU", "Eurozone", "OECD"] },
  { code: "BGR", name: "Bulgaria", slug: "bulgaria", externalIds: { weo: { countryId: "BGR" }, unctad: { m49: "100" }, worldBank: { countryId: "BGR" } }, region: "Europe", categories: ["EU", "Eurozone"] },
  { code: "HRV", name: "Croatia", slug: "croatia", externalIds: { weo: { countryId: "HRV" }, unctad: { m49: "191" }, worldBank: { countryId: "HRV" } }, region: "Europe", categories: ["EU", "Eurozone"] },
  { code: "CYP", name: "Cyprus", slug: "cyprus", externalIds: { weo: { countryId: "CYP" }, unctad: { m49: "196" }, worldBank: { countryId: "CYP" } }, region: "Europe", categories: ["EU", "Eurozone"] },
  { code: "CZE", name: "Czechia", slug: "czechia", externalIds: { weo: { countryId: "CZE" }, unctad: { m49: "203" }, worldBank: { countryId: "CZE" } }, aliases: ["Czech Republic"], region: "Europe", categories: ["EU", "OECD"] },
  { code: "DNK", name: "Denmark", slug: "denmark", externalIds: { weo: { countryId: "DNK" }, unctad: { m49: "208" }, worldBank: { countryId: "DNK" } }, region: "Europe", categories: ["EU", "OECD"] },
  { code: "EST", name: "Estonia", slug: "estonia", externalIds: { weo: { countryId: "EST" }, unctad: { m49: "233" }, worldBank: { countryId: "EST" } }, region: "Europe", categories: ["EU", "Eurozone", "OECD"] },
  { code: "FIN", name: "Finland", slug: "finland", externalIds: { weo: { countryId: "FIN" }, unctad: { m49: "246" }, worldBank: { countryId: "FIN" } }, region: "Europe", categories: ["EU", "Eurozone", "OECD"] },
  { code: "GRC", name: "Greece", slug: "greece", externalIds: { weo: { countryId: "GRC" }, unctad: { m49: "300" }, worldBank: { countryId: "GRC" } }, region: "Europe", categories: ["EU", "Eurozone", "OECD"] },
  { code: "HUN", name: "Hungary", slug: "hungary", externalIds: { weo: { countryId: "HUN" }, unctad: { m49: "348" }, worldBank: { countryId: "HUN" } }, region: "Europe", categories: ["EU", "OECD"] },
  { code: "IRL", name: "Ireland", slug: "ireland", externalIds: { weo: { countryId: "IRL" }, unctad: { m49: "372" }, worldBank: { countryId: "IRL" } }, region: "Europe", categories: ["EU", "Eurozone", "OECD"] },
  { code: "LVA", name: "Latvia", slug: "latvia", externalIds: { weo: { countryId: "LVA" }, unctad: { m49: "428" }, worldBank: { countryId: "LVA" } }, region: "Europe", categories: ["EU", "Eurozone", "OECD"] },
  { code: "LTU", name: "Lithuania", slug: "lithuania", externalIds: { weo: { countryId: "LTU" }, unctad: { m49: "440" }, worldBank: { countryId: "LTU" } }, region: "Europe", categories: ["EU", "Eurozone", "OECD"] },
  { code: "LUX", name: "Luxembourg", slug: "luxembourg", externalIds: { weo: { countryId: "LUX" }, unctad: { m49: "442" }, worldBank: { countryId: "LUX" } }, region: "Europe", categories: ["EU", "Eurozone", "OECD"] },
  { code: "MLT", name: "Malta", slug: "malta", externalIds: { weo: { countryId: "MLT" }, unctad: { m49: "470" }, worldBank: { countryId: "MLT" } }, region: "Europe", categories: ["EU", "Eurozone"] },
  { code: "NLD", name: "Netherlands", slug: "netherlands", externalIds: { weo: { countryId: "NLD" }, unctad: { m49: "528" }, worldBank: { countryId: "NLD" } }, aliases: ["Holland"], region: "Europe", categories: ["EU", "Eurozone", "OECD"] },
  { code: "POL", name: "Poland", slug: "poland", externalIds: { weo: { countryId: "POL" }, unctad: { m49: "616" }, worldBank: { countryId: "POL" } }, region: "Europe", categories: ["EU", "OECD"] },
  { code: "PRT", name: "Portugal", slug: "portugal", externalIds: { weo: { countryId: "PRT" }, unctad: { m49: "620" }, worldBank: { countryId: "PRT" } }, region: "Europe", categories: ["EU", "Eurozone", "OECD"] },
  { code: "ROU", name: "Romania", slug: "romania", externalIds: { weo: { countryId: "ROU" }, unctad: { m49: "642" }, worldBank: { countryId: "ROU" } }, region: "Europe", categories: ["EU"] },
  { code: "SVK", name: "Slovakia", slug: "slovakia", externalIds: { weo: { countryId: "SVK" }, unctad: { m49: "703" }, worldBank: { countryId: "SVK" } }, region: "Europe", categories: ["EU", "Eurozone", "OECD"] },
  { code: "SVN", name: "Slovenia", slug: "slovenia", externalIds: { weo: { countryId: "SVN" }, unctad: { m49: "705" }, worldBank: { countryId: "SVN" } }, region: "Europe", categories: ["EU", "Eurozone", "OECD"] },
  { code: "ESP", name: "Spain", slug: "spain", externalIds: { weo: { countryId: "ESP" }, unctad: { m49: "724" }, worldBank: { countryId: "ESP" } }, region: "Europe", categories: ["EU", "Eurozone", "OECD"] },
  { code: "SWE", name: "Sweden", slug: "sweden", externalIds: { weo: { countryId: "SWE" }, unctad: { m49: "752" }, worldBank: { countryId: "SWE" } }, region: "Europe", categories: ["EU", "OECD"] },
  { code: "BRN", name: "Brunei", slug: "brunei", externalIds: { weo: { countryId: "BRN" }, unctad: { m49: "096" }, worldBank: { countryId: "BRN" } }, region: "Asia", categories: ["ASEAN"] },
  { code: "KHM", name: "Cambodia", slug: "cambodia", externalIds: { weo: { countryId: "KHM" }, unctad: { m49: "116" }, worldBank: { countryId: "KHM" } }, region: "Asia", categories: ["ASEAN"] },
  { code: "LAO", name: "Laos", slug: "laos", externalIds: { weo: { countryId: "LAO" }, unctad: { m49: "418" }, worldBank: { countryId: "LAO" } }, region: "Asia", categories: ["ASEAN"] },
  { code: "MYS", name: "Malaysia", slug: "malaysia", externalIds: { weo: { countryId: "MYS" }, unctad: { m49: "458" }, worldBank: { countryId: "MYS" } }, region: "Asia", categories: ["ASEAN"] },
  { code: "MMR", name: "Myanmar", slug: "myanmar", externalIds: { weo: { countryId: "MMR" }, unctad: { m49: "104" }, worldBank: { countryId: "MMR" } }, aliases: ["Burma"], region: "Asia", categories: ["ASEAN"] },
  { code: "PHL", name: "Philippines", slug: "philippines", externalIds: { weo: { countryId: "PHL" }, unctad: { m49: "608" }, worldBank: { countryId: "PHL" } }, region: "Asia", categories: ["ASEAN"] },
  { code: "SGP", name: "Singapore", slug: "singapore", externalIds: { weo: { countryId: "SGP" }, unctad: { m49: "702" }, worldBank: { countryId: "SGP" } }, region: "Asia", categories: ["ASEAN"] },
  { code: "THA", name: "Thailand", slug: "thailand", externalIds: { weo: { countryId: "THA" }, unctad: { m49: "764" }, worldBank: { countryId: "THA" } }, region: "Asia", categories: ["ASEAN"] },
  { code: "TLS", name: "Timor-Leste", slug: "timor-leste", externalIds: { weo: { countryId: "TLS" }, unctad: { m49: "626" }, worldBank: { countryId: "TLS" } }, aliases: ["East Timor"], region: "Asia", categories: ["ASEAN"] },
  { code: "VNM", name: "Vietnam", slug: "vietnam", externalIds: { weo: { countryId: "VNM" }, unctad: { m49: "704" }, worldBank: { countryId: "VNM" } }, region: "Asia", categories: ["ASEAN"] },
  { code: "WBG", name: "Palestine", slug: "palestine", externalIds: { weo: { countryId: "WBG" }, unctad: { m49: "275" } }, aliases: ["State of Palestine", "West Bank and Gaza"], region: "Asia", categories: [] },
  { code: "DZA", name: "Algeria", slug: "algeria", externalIds: { weo: { countryId: "DZA" }, unctad: { m49: "012" }, worldBank: { countryId: "DZA" } }, region: "Africa", categories: ["AU"] },
  { code: "AGO", name: "Angola", slug: "angola", externalIds: { weo: { countryId: "AGO" }, unctad: { m49: "024" }, worldBank: { countryId: "AGO" } }, region: "Africa", categories: ["AU"] },
  { code: "BEN", name: "Benin", slug: "benin", externalIds: { weo: { countryId: "BEN" }, unctad: { m49: "204" }, worldBank: { countryId: "BEN" } }, region: "Africa", categories: ["AU"] },
  { code: "BWA", name: "Botswana", slug: "botswana", externalIds: { weo: { countryId: "BWA" }, unctad: { m49: "072" }, worldBank: { countryId: "BWA" } }, region: "Africa", categories: ["AU"] },
  { code: "BFA", name: "Burkina Faso", slug: "burkina-faso", externalIds: { weo: { countryId: "BFA" }, unctad: { m49: "854" }, worldBank: { countryId: "BFA" } }, region: "Africa", categories: ["AU"] },
  { code: "BDI", name: "Burundi", slug: "burundi", externalIds: { weo: { countryId: "BDI" }, unctad: { m49: "108" }, worldBank: { countryId: "BDI" } }, region: "Africa", categories: ["AU"] },
  { code: "CPV", name: "Cabo Verde", slug: "cabo-verde", externalIds: { weo: { countryId: "CPV" }, unctad: { m49: "132" }, worldBank: { countryId: "CPV" } }, aliases: ["Cape Verde"], region: "Africa", categories: ["AU"] },
  { code: "CMR", name: "Cameroon", slug: "cameroon", externalIds: { weo: { countryId: "CMR" }, unctad: { m49: "120" }, worldBank: { countryId: "CMR" } }, region: "Africa", categories: ["AU"] },
  { code: "CAF", name: "Central African Republic", slug: "central-african-republic", externalIds: { weo: { countryId: "CAF" }, unctad: { m49: "140" }, worldBank: { countryId: "CAF" } }, region: "Africa", categories: ["AU"] },
  { code: "TCD", name: "Chad", slug: "chad", externalIds: { weo: { countryId: "TCD" }, unctad: { m49: "148" }, worldBank: { countryId: "TCD" } }, region: "Africa", categories: ["AU"] },
  { code: "COM", name: "Comoros", slug: "comoros", externalIds: { weo: { countryId: "COM" }, unctad: { m49: "174" }, worldBank: { countryId: "COM" } }, region: "Africa", categories: ["AU"] },
  { code: "COG", name: "Republic of the Congo", slug: "republic-of-the-congo", externalIds: { weo: { countryId: "COG" }, unctad: { m49: "178" }, worldBank: { countryId: "COG" } }, region: "Africa", categories: ["AU"] },
  { code: "COD", name: "Democratic Republic of the Congo", slug: "democratic-republic-of-the-congo", externalIds: { weo: { countryId: "COD" }, unctad: { m49: "180" }, worldBank: { countryId: "COD" } }, aliases: ["DRC"], region: "Africa", categories: ["AU"] },
  { code: "CIV", name: "Côte d’Ivoire", slug: "cote-divoire", externalIds: { weo: { countryId: "CIV" }, unctad: { m49: "384" }, worldBank: { countryId: "CIV" } }, aliases: ["Ivory Coast"], region: "Africa", categories: ["AU"] },
  { code: "DJI", name: "Djibouti", slug: "djibouti", externalIds: { weo: { countryId: "DJI" }, unctad: { m49: "262" }, worldBank: { countryId: "DJI" } }, region: "Africa", categories: ["AU"] },
  { code: "EGY", name: "Egypt", slug: "egypt", externalIds: { weo: { countryId: "EGY" }, unctad: { m49: "818" }, worldBank: { countryId: "EGY" } }, region: "Africa", categories: ["AU", "BRICS"] },
  { code: "GNQ", name: "Equatorial Guinea", slug: "equatorial-guinea", externalIds: { weo: { countryId: "GNQ" }, unctad: { m49: "226" }, worldBank: { countryId: "GNQ" } }, region: "Africa", categories: ["AU"] },
  { code: "ERI", name: "Eritrea", slug: "eritrea", externalIds: { weo: { countryId: "ERI" }, unctad: { m49: "232" }, worldBank: { countryId: "ERI" } }, region: "Africa", categories: ["AU"] },
  { code: "SWZ", name: "Eswatini", slug: "eswatini", externalIds: { weo: { countryId: "SWZ" }, unctad: { m49: "748" }, worldBank: { countryId: "SWZ" } }, aliases: ["Swaziland"], region: "Africa", categories: ["AU"] },
  { code: "ETH", name: "Ethiopia", slug: "ethiopia", externalIds: { weo: { countryId: "ETH" }, unctad: { m49: "231" }, worldBank: { countryId: "ETH" } }, region: "Africa", categories: ["AU", "BRICS"] },
  { code: "GAB", name: "Gabon", slug: "gabon", externalIds: { weo: { countryId: "GAB" }, unctad: { m49: "266" }, worldBank: { countryId: "GAB" } }, region: "Africa", categories: ["AU"] },
  { code: "GMB", name: "Gambia", slug: "gambia", externalIds: { weo: { countryId: "GMB" }, unctad: { m49: "270" }, worldBank: { countryId: "GMB" } }, region: "Africa", categories: ["AU"] },
  { code: "GHA", name: "Ghana", slug: "ghana", externalIds: { weo: { countryId: "GHA" }, unctad: { m49: "288" }, worldBank: { countryId: "GHA" } }, region: "Africa", categories: ["AU"] },
  { code: "GIN", name: "Guinea", slug: "guinea", externalIds: { weo: { countryId: "GIN" }, unctad: { m49: "324" }, worldBank: { countryId: "GIN" } }, region: "Africa", categories: ["AU"] },
  { code: "GNB", name: "Guinea-Bissau", slug: "guinea-bissau", externalIds: { weo: { countryId: "GNB" }, unctad: { m49: "624" }, worldBank: { countryId: "GNB" } }, region: "Africa", categories: ["AU"] },
  { code: "KEN", name: "Kenya", slug: "kenya", externalIds: { weo: { countryId: "KEN" }, unctad: { m49: "404" }, worldBank: { countryId: "KEN" } }, region: "Africa", categories: ["AU"] },
  { code: "LSO", name: "Lesotho", slug: "lesotho", externalIds: { weo: { countryId: "LSO" }, unctad: { m49: "426" }, worldBank: { countryId: "LSO" } }, region: "Africa", categories: ["AU"] },
  { code: "LBR", name: "Liberia", slug: "liberia", externalIds: { weo: { countryId: "LBR" }, unctad: { m49: "430" }, worldBank: { countryId: "LBR" } }, region: "Africa", categories: ["AU"] },
  { code: "LBY", name: "Libya", slug: "libya", externalIds: { weo: { countryId: "LBY" }, unctad: { m49: "434" }, worldBank: { countryId: "LBY" } }, region: "Africa", categories: ["AU"] },
  { code: "MDG", name: "Madagascar", slug: "madagascar", externalIds: { weo: { countryId: "MDG" }, unctad: { m49: "450" }, worldBank: { countryId: "MDG" } }, region: "Africa", categories: ["AU"] },
  { code: "MWI", name: "Malawi", slug: "malawi", externalIds: { weo: { countryId: "MWI" }, unctad: { m49: "454" }, worldBank: { countryId: "MWI" } }, region: "Africa", categories: ["AU"] },
  { code: "MYT", name: "Mayotte", slug: "mayotte", region: "Africa", categories: [] },
  { code: "MLI", name: "Mali", slug: "mali", externalIds: { weo: { countryId: "MLI" }, unctad: { m49: "466" }, worldBank: { countryId: "MLI" } }, region: "Africa", categories: ["AU"] },
  { code: "MRT", name: "Mauritania", slug: "mauritania", externalIds: { weo: { countryId: "MRT" }, unctad: { m49: "478" }, worldBank: { countryId: "MRT" } }, region: "Africa", categories: ["AU"] },
  { code: "MUS", name: "Mauritius", slug: "mauritius", externalIds: { weo: { countryId: "MUS" }, unctad: { m49: "480" }, worldBank: { countryId: "MUS" } }, region: "Africa", categories: ["AU"] },
  { code: "MAR", name: "Morocco", slug: "morocco", externalIds: { weo: { countryId: "MAR" }, unctad: { m49: "504" }, worldBank: { countryId: "MAR" } }, region: "Africa", categories: ["AU"] },
  { code: "MOZ", name: "Mozambique", slug: "mozambique", externalIds: { weo: { countryId: "MOZ" }, unctad: { m49: "508" }, worldBank: { countryId: "MOZ" } }, region: "Africa", categories: ["AU"] },
  { code: "NAM", name: "Namibia", slug: "namibia", externalIds: { weo: { countryId: "NAM" }, unctad: { m49: "516" }, worldBank: { countryId: "NAM" } }, region: "Africa", categories: ["AU"] },
  { code: "NER", name: "Niger", slug: "niger", externalIds: { weo: { countryId: "NER" }, unctad: { m49: "562" }, worldBank: { countryId: "NER" } }, region: "Africa", categories: ["AU"] },
  { code: "NGA", name: "Nigeria", slug: "nigeria", externalIds: { weo: { countryId: "NGA" }, unctad: { m49: "566" }, worldBank: { countryId: "NGA" } }, region: "Africa", categories: ["AU"] },
  { code: "RWA", name: "Rwanda", slug: "rwanda", externalIds: { weo: { countryId: "RWA" }, unctad: { m49: "646" }, worldBank: { countryId: "RWA" } }, region: "Africa", categories: ["AU"] },
  { code: "REU", name: "Réunion", slug: "reunion", externalIds: { unctad: { m49: "638" } }, region: "Africa", categories: [] },
  { code: "SHN", name: "Saint Helena", slug: "saint-helena", externalIds: { unctad: { m49: "654" } }, region: "Africa", categories: [] },
  { code: "STP", name: "São Tomé and Príncipe", slug: "sao-tome-and-principe", externalIds: { weo: { countryId: "STP" }, unctad: { m49: "678" }, worldBank: { countryId: "STP" } }, region: "Africa", categories: ["AU"] },
  { code: "SEN", name: "Senegal", slug: "senegal", externalIds: { weo: { countryId: "SEN" }, unctad: { m49: "686" }, worldBank: { countryId: "SEN" } }, region: "Africa", categories: ["AU"] },
  { code: "SYC", name: "Seychelles", slug: "seychelles", externalIds: { weo: { countryId: "SYC" }, unctad: { m49: "690" }, worldBank: { countryId: "SYC" } }, region: "Africa", categories: ["AU"] },
  { code: "SLE", name: "Sierra Leone", slug: "sierra-leone", externalIds: { weo: { countryId: "SLE" }, unctad: { m49: "694" }, worldBank: { countryId: "SLE" } }, region: "Africa", categories: ["AU"] },
  { code: "SOM", name: "Somalia", slug: "somalia", externalIds: { weo: { countryId: "SOM" }, unctad: { m49: "706" }, worldBank: { countryId: "SOM" } }, region: "Africa", categories: ["AU"] },
  { code: "SSD", name: "South Sudan", slug: "south-sudan", externalIds: { weo: { countryId: "SSD" }, unctad: { m49: "728" }, worldBank: { countryId: "SSD" } }, region: "Africa", categories: ["AU"] },
  { code: "SDN", name: "Sudan", slug: "sudan", externalIds: { weo: { countryId: "SDN" }, unctad: { m49: "729" }, worldBank: { countryId: "SDN" } }, region: "Africa", categories: ["AU"] },
  { code: "TZA", name: "Tanzania", slug: "tanzania", externalIds: { weo: { countryId: "TZA" }, unctad: { m49: "834" }, worldBank: { countryId: "TZA" } }, region: "Africa", categories: ["AU"] },
  { code: "TGO", name: "Togo", slug: "togo", externalIds: { weo: { countryId: "TGO" }, unctad: { m49: "768" }, worldBank: { countryId: "TGO" } }, region: "Africa", categories: ["AU"] },
  { code: "TUN", name: "Tunisia", slug: "tunisia", externalIds: { weo: { countryId: "TUN" }, unctad: { m49: "788" }, worldBank: { countryId: "TUN" } }, region: "Africa", categories: ["AU"] },
  { code: "UGA", name: "Uganda", slug: "uganda", externalIds: { weo: { countryId: "UGA" }, unctad: { m49: "800" }, worldBank: { countryId: "UGA" } }, region: "Africa", categories: ["AU"] },
  { code: "ZMB", name: "Zambia", slug: "zambia", externalIds: { weo: { countryId: "ZMB" }, unctad: { m49: "894" }, worldBank: { countryId: "ZMB" } }, region: "Africa", categories: ["AU"] },
  { code: "ZWE", name: "Zimbabwe", slug: "zimbabwe", externalIds: { weo: { countryId: "ZWE" }, unctad: { m49: "716" }, worldBank: { countryId: "ZWE" } }, region: "Africa", categories: ["AU"] },
];
