export const currencyCodesByCountry = {
  ABW: "AWG",
  AFG: "AFN",
  AIA: "XCD",
  AGO: "AOA",
  ALB: "ALL",
  AND: "EUR",
  ARE: "AED",
  ARG: "ARS",
  ARM: "AMD",
  ASM: "USD",
  ATG: "XCD",
  AUS: "AUD",
  AUT: "EUR",
  AZE: "AZN",
  BDI: "BIF",
  BEL: "EUR",
  BEN: "XOF",
  BFA: "XOF",
  BGD: "BDT",
  BGR: "BGN",
  BHR: "BHD",
  BHS: "BSD",
  BIH: "BAM",
  BLR: "BYN",
  BMU: "BMD",
  BLZ: "BZD",
  BOL: "BOB",
  BRA: "BRL",
  BRB: "BBD",
  BRN: "BND",
  BTN: "BTN",
  BWA: "BWP",
  CAF: "XAF",
  CAN: "CAD",
  CHE: "CHF",
  CHL: "CLP",
  CHN: "CNY",
  CIV: "XOF",
  CMR: "XAF",
  COD: "CDF",
  COG: "XAF",
  COK: "NZD",
  COL: "COP",
  COM: "KMF",
  CPV: "CVE",
  CRI: "CRC",
  CUB: "CUP",
  CUW: "ANG",
  CYM: "KYD",
  CYP: "EUR",
  CZE: "CZK",
  DEU: "EUR",
  DJI: "DJF",
  DMA: "XCD",
  DNK: "DKK",
  DOM: "DOP",
  DZA: "DZD",
  ECU: "USD",
  EGY: "EGP",
  ERI: "ERN",
  ESP: "EUR",
  EST: "EUR",
  ETH: "ETB",
  FIN: "EUR",
  FJI: "FJD",
  FLK: "FKP",
  FRA: "EUR",
  FRO: "DKK",
  FSM: "USD",
  GAB: "XAF",
  GBR: "GBP",
  GEO: "GEL",
  GHA: "GHS",
  GIB: "GIP",
  GIN: "GNF",
  GLP: "EUR",
  GMB: "GMD",
  GNB: "XOF",
  GNQ: "XAF",
  GRC: "EUR",
  GRD: "XCD",
  GRL: "DKK",
  GTM: "GTQ",
  GUF: "EUR",
  GUM: "USD",
  GUY: "GYD",
  HKG: "HKD",
  HND: "HNL",
  HRV: "EUR",
  HTI: "HTG",
  HUN: "HUF",
  IDN: "IDR",
  IMN: "GBP",
  IND: "INR",
  IRL: "EUR",
  IRN: "IRR",
  IRQ: "IQD",
  ISL: "ISK",
  ISR: "ILS",
  ITA: "EUR",
  JAM: "JMD",
  JOR: "JOD",
  JPN: "JPY",
  KAZ: "KZT",
  KEN: "KES",
  KGZ: "KGS",
  KHM: "KHR",
  KIR: "AUD",
  KNA: "XCD",
  KOR: "KRW",
  KOS: "EUR",
  KWT: "KWD",
  LAO: "LAK",
  LBN: "LBP",
  LBR: "LRD",
  LBY: "LYD",
  LCA: "XCD",
  LIE: "CHF",
  LKA: "LKR",
  LSO: "LSL",
  LTU: "EUR",
  LUX: "EUR",
  LVA: "EUR",
  MAC: "MOP",
  MAR: "MAD",
  MAF: "EUR",
  MCO: "EUR",
  MDA: "MDL",
  MDG: "MGA",
  MDV: "MVR",
  MEX: "MXN",
  MHL: "USD",
  MKD: "MKD",
  MLI: "XOF",
  MLT: "EUR",
  MMR: "MMK",
  MNE: "EUR",
  MNG: "MNT",
  MNP: "USD",
  MOZ: "MZN",
  MRT: "MRU",
  MSR: "XCD",
  MTQ: "EUR",
  MUS: "MUR",
  MWI: "MWK",
  MYS: "MYR",
  MYT: "EUR",
  NAM: "NAD",
  NCL: "XPF",
  NER: "XOF",
  NGA: "NGN",
  NIC: "NIO",
  NIU: "NZD",
  NLD: "EUR",
  NOR: "NOK",
  NPL: "NPR",
  NRU: "AUD",
  NZL: "NZD",
  OMN: "OMR",
  PAK: "PKR",
  PAN: "PAB",
  PCN: "NZD",
  PER: "PEN",
  PHL: "PHP",
  PLW: "USD",
  PNG: "PGK",
  POL: "PLN",
  PRK: "KPW",
  PRI: "USD",
  PRT: "EUR",
  PRY: "PYG",
  PYF: "XPF",
  QAT: "QAR",
  REU: "EUR",
  ROU: "RON",
  RUS: "RUB",
  RWA: "RWF",
  SAU: "SAR",
  SDN: "SDG",
  SEN: "XOF",
  SGP: "SGD",
  SHN: "SHP",
  SLB: "SBD",
  SLE: "SLE",
  SLV: "USD",
  SMR: "EUR",
  SOM: "SOS",
  SPM: "EUR",
  SRB: "RSD",
  SSD: "SSP",
  STP: "STN",
  SUR: "SRD",
  SVK: "EUR",
  SVN: "EUR",
  SWE: "SEK",
  SWZ: "SZL",
  SXM: "ANG",
  SYC: "SCR",
  SYR: "SYP",
  TCA: "USD",
  TCD: "XAF",
  TGO: "XOF",
  THA: "THB",
  TJK: "TJS",
  TKL: "NZD",
  TKM: "TMT",
  TLS: "USD",
  TON: "TOP",
  TTO: "TTD",
  TUN: "TND",
  TUR: "TRY",
  TUV: "AUD",
  TWN: "TWD",
  TZA: "TZS",
  UGA: "UGX",
  UKR: "UAH",
  URY: "UYU",
  USA: "USD",
  UZB: "UZS",
  VAT: "EUR",
  VCT: "XCD",
  VEN: "VES",
  VGB: "USD",
  VIR: "USD",
  VNM: "VND",
  VUT: "VUV",
  WBG: "ILS",
  WLF: "XPF",
  WSM: "WST",
  YEM: "YER",
  ZAF: "ZAR",
  ZMB: "ZMW",
  ZWE: "ZWG",
};

export const currencyDetailsByCode = {
  AWG: { name: "Aruban florin" },
  AFN: { name: "Afghan afghani" },
  XCD: { name: "East Caribbean dollar" },
  AOA: { name: "Angolan kwanza" },
  ALL: { name: "Albanian lek" },
  EUR: { name: "Euro", symbol: "€" },
  AED: { name: "United Arab Emirates dirham" },
  ARS: { name: "Argentine peso" },
  AMD: { name: "Armenian dram" },
  USD: { name: "United States dollar", symbol: "$" },
  AUD: { name: "Australian dollar" },
  AZN: { name: "Azerbaijani manat" },
  BIF: { name: "Burundian franc" },
  XOF: { name: "West African CFA franc" },
  BDT: { name: "Bangladeshi taka" },
  BGN: { name: "Bulgarian lev" },
  BHD: { name: "Bahraini dinar" },
  BSD: { name: "Bahamian dollar" },
  BAM: { name: "Bosnia and Herzegovina convertible mark" },
  BYN: { name: "Belarusian ruble" },
  BMD: { name: "Bermudian dollar" },
  BZD: { name: "Belize dollar" },
  BOB: { name: "Boliviano" },
  BRL: { name: "Brazilian real" },
  BBD: { name: "Barbados dollar" },
  BND: { name: "Brunei dollar" },
  BTN: { name: "Bhutanese ngultrum" },
  BWP: { name: "Botswana pula" },
  XAF: { name: "Central African CFA franc" },
  CAD: { name: "Canadian dollar" },
  CHF: { name: "Swiss franc" },
  CLP: { name: "Chilean peso" },
  CNY: { name: "Renminbi" },
  CDF: { name: "Congolese franc" },
  NZD: { name: "New Zealand dollar" },
  COP: { name: "Colombian peso" },
  KMF: { name: "Comorian franc" },
  CVE: { name: "Cape Verdean escudo" },
  CRC: { name: "Costa Rican colon" },
  CUP: { name: "Cuban peso" },
  ANG: { name: "Netherlands Antillean guilder" },
  KYD: { name: "Cayman Islands dollar" },
  CZK: { name: "Czech koruna" },
  DJF: { name: "Djiboutian franc" },
  DKK: { name: "Danish krone" },
  DOP: { name: "Dominican peso" },
  DZD: { name: "Algerian dinar" },
  EGP: { name: "Egyptian pound" },
  ERN: { name: "Eritrean nakfa" },
  ETB: { name: "Ethiopian birr" },
  FJD: { name: "Fijian dollar" },
  FKP: { name: "Falkland Islands pound" },
  GBP: { name: "Pound sterling" },
  GEL: { name: "Georgian lari" },
  GHS: { name: "Ghanaian cedi" },
  GIP: { name: "Gibraltar pound" },
  GNF: { name: "Guinean franc" },
  GMD: { name: "Gambian dalasi" },
  GTQ: { name: "Guatemalan quetzal" },
  GYD: { name: "Guyanese dollar" },
  HKD: { name: "Hong Kong dollar" },
  HNL: { name: "Honduran lempira" },
  HTG: { name: "Haitian gourde" },
  HUF: { name: "Hungarian forint" },
  IDR: { name: "Indonesian rupiah" },
  INR: { name: "Indian rupee" },
  IRR: { name: "Iranian rial" },
  IQD: { name: "Iraqi dinar" },
  ISK: { name: "Icelandic króna" },
  ILS: { name: "Israeli new shekel" },
  JMD: { name: "Jamaican dollar" },
  JOD: { name: "Jordanian dinar" },
  JPY: { name: "Japanese Yen" },
  KZT: { name: "Kazakhstani tenge" },
  KES: { name: "Kenyan shilling" },
  KGS: { name: "Kyrgyzstani som" },
  KHR: { name: "Cambodian riel" },
  KRW: { name: "South Korean won" },
  KWD: { name: "Kuwaiti dinar" },
  LAK: { name: "Lao kip" },
  LBP: { name: "Lebanese pound" },
  LRD: { name: "Liberian dollar" },
  LYD: { name: "Libyan dinar" },
  LKR: { name: "Sri Lankan rupee" },
  LSL: { name: "Lesotho loti" },
  MOP: { name: "Macanese pataca" },
  MAD: { name: "Moroccan dirham" },
  MDL: { name: "Moldovan leu" },
  MGA: { name: "Malagasy ariary" },
  MVR: { name: "Maldivian rufiyaa" },
  MXN: { name: "Mexican peso" },
  MKD: { name: "Macedonian denar" },
  MMK: { name: "Myanmar kyat" },
  MNT: { name: "Mongolian tögrög" },
  MZN: { name: "Mozambican metical" },
  MRU: { name: "Mauritanian ouguiya" },
  MUR: { name: "Mauritian rupee" },
  MWK: { name: "Malawian kwacha" },
  MYR: { name: "Malaysian ringgit" },
  NAD: { name: "Namibian dollar" },
  XPF: { name: "CFP franc" },
  NGN: { name: "Nigerian naira" },
  NIO: { name: "Nicaraguan córdoba" },
  NOK: { name: "Norwegian krone" },
  NPR: { name: "Nepalese rupee" },
  OMR: { name: "Omani rial" },
  PKR: { name: "Pakistani rupee" },
  PAB: { name: "Panamanian balboa" },
  PEN: { name: "Peruvian sol" },
  PHP: { name: "Philippine peso" },
  PGK: { name: "Papua New Guinean kina" },
  PLN: { name: "Polish złoty" },
  KPW: { name: "North Korean won" },
  PYG: { name: "Paraguayan guaraní" },
  QAR: { name: "Qatari riyal" },
  RON: { name: "Romanian leu" },
  RUB: { name: "Russian ruble" },
  RWF: { name: "Rwandan franc" },
  SAR: { name: "Saudi riyal" },
  SDG: { name: "Sudanese pound" },
  SGD: { name: "Singapore dollar" },
  SHP: { name: "Saint Helena pound" },
  SBD: { name: "Solomon Islands dollar" },
  SLE: { name: "Sierra Leonean leone" },
  SOS: { name: "Somali shilling" },
  RSD: { name: "Serbian dinar" },
  SSP: { name: "South Sudanese pound" },
  STN: { name: "São Tomé and Príncipe dobra" },
  SRD: { name: "Surinamese dollar" },
  SEK: { name: "Swedish krona" },
  SZL: { name: "Swazi lilangeni" },
  SCR: { name: "Seychellois rupee" },
  SYP: { name: "Syrian pound" },
  THB: { name: "Thai baht" },
  TJS: { name: "Tajikistani somoni" },
  TMT: { name: "Turkmenistan manat" },
  TOP: { name: "Tongan paʻanga" },
  TTD: { name: "Trinidad and Tobago dollar" },
  TND: { name: "Tunisian dinar" },
  TRY: { name: "Turkish lira" },
  TWD: { name: "New Taiwan dollar" },
  TZS: { name: "Tanzanian shilling" },
  UGX: { name: "Ugandan shilling" },
  UAH: { name: "Ukrainian hryvnia" },
  UYU: { name: "Uruguayan peso" },
  UZS: { name: "Uzbekistani sum" },
  VES: { name: "Venezuelan sovereign bolívar" },
  VND: { name: "Vietnamese đồng" },
  VUV: { name: "Vanuatu vatu" },
  WST: { name: "Samoan tālā" },
  YER: { name: "Yemeni rial" },
  ZAR: { name: "South African rand" },
  ZMW: { name: "Zambian kwacha" },
  ZWG: { name: "Zimbabwe Gold" },
  XCG: { name: "Caribbean guilder" },
  "Int$": { symbol: "$" },
};

export const currencyNamesByCode = Object.fromEntries(
  Object.entries(currencyDetailsByCode)
    .filter(([, details]) => details.name)
    .map(([code, details]) => [code, details.name]),
);

export function getCurrencyCode(countryCode) {
  return currencyCodesByCountry[countryCode] ?? "";
}

export function getCurrencyName(currencyCode) {
  return currencyDetailsByCode[currencyCode]?.name ?? "";
}

export function getCurrencySymbol(currencyCode) {
  return currencyDetailsByCode[currencyCode]?.symbol ?? "";
}

export function getCountryCurrencyDisplay(countryCode) {
  const currencyCode = getCurrencyCode(countryCode);
  const currencyName = getCurrencyName(currencyCode);

  if (!currencyCode) {
    return "";
  }

  return currencyName ? `${currencyName} (${currencyCode})` : currencyCode;
}
