export const currencyCodesByCountry = {
  ABW: "AWG",
  AFG: "AFN",
  AIA: "XCD",
  AGO: "AOA",
  ALB: "ALL",
  AND: "EUR",
  ARE: "AED",
  ARG: "ARS",
  ARM: "AMD",
  ASM: "USD",
  ATG: "XCD",
  AUS: "AUD",
  AUT: "EUR",
  AZE: "AZN",
  BDI: "BIF",
  BEL: "EUR",
  BEN: "XOF",
  BFA: "XOF",
  BGD: "BDT",
  BGR: "BGN",
  BHR: "BHD",
  BHS: "BSD",
  BIH: "BAM",
  BLR: "BYN",
  BMU: "BMD",
  BLZ: "BZD",
  BOL: "BOB",
  BRA: "BRL",
  BRB: "BBD",
  BRN: "BND",
  BTN: "BTN",
  BWA: "BWP",
  CAF: "XAF",
  CAN: "CAD",
  CHE: "CHF",
  CHL: "CLP",
  CHN: "CNY",
  CIV: "XOF",
  CMR: "XAF",
  COD: "CDF",
  COG: "XAF",
  COK: "NZD",
  COL: "COP",
  COM: "KMF",
  CPV: "CVE",
  CRI: "CRC",
  CUB: "CUP",
  CUW: "ANG",
  CYM: "KYD",
  CYP: "EUR",
  CZE: "CZK",
  DEU: "EUR",
  DJI: "DJF",
  DMA: "XCD",
  DNK: "DKK",
  DOM: "DOP",
  DZA: "DZD",
  ECU: "USD",
  EGY: "EGP",
  ERI: "ERN",
  ESP: "EUR",
  EST: "EUR",
  ETH: "ETB",
  FIN: "EUR",
  FJI: "FJD",
  FLK: "FKP",
  FRA: "EUR",
  FRO: "DKK",
  FSM: "USD",
  GAB: "XAF",
  GBR: "GBP",
  GEO: "GEL",
  GHA: "GHS",
  GIB: "GIP",
  GIN: "GNF",
  GLP: "EUR",
  GMB: "GMD",
  GNB: "XOF",
  GNQ: "XAF",
  GRC: "EUR",
  GRD: "XCD",
  GRL: "DKK",
  GTM: "GTQ",
  GUF: "EUR",
  GUM: "USD",
  GUY: "GYD",
  HKG: "HKD",
  HND: "HNL",
  HRV: "EUR",
  HTI: "HTG",
  HUN: "HUF",
  IDN: "IDR",
  IMN: "GBP",
  IND: "INR",
  IRL: "EUR",
  IRN: "IRR",
  IRQ: "IQD",
  ISL: "ISK",
  ISR: "ILS",
  ITA: "EUR",
  JAM: "JMD",
  JOR: "JOD",
  JPN: "JPY",
  KAZ: "KZT",
  KEN: "KES",
  KGZ: "KGS",
  KHM: "KHR",
  KIR: "AUD",
  KNA: "XCD",
  KOR: "KRW",
  KOS: "EUR",
  KWT: "KWD",
  LAO: "LAK",
  LBN: "LBP",
  LBR: "LRD",
  LBY: "LYD",
  LCA: "XCD",
  LIE: "CHF",
  LKA: "LKR",
  LSO: "LSL",
  LTU: "EUR",
  LUX: "EUR",
  LVA: "EUR",
  MAC: "MOP",
  MAR: "MAD",
  MAF: "EUR",
  MCO: "EUR",
  MDA: "MDL",
  MDG: "MGA",
  MDV: "MVR",
  MEX: "MXN",
  MHL: "USD",
  MKD: "MKD",
  MLI: "XOF",
  MLT: "EUR",
  MMR: "MMK",
  MNE: "EUR",
  MNG: "MNT",
  MNP: "USD",
  MOZ: "MZN",
  MRT: "MRU",
  MSR: "XCD",
  MTQ: "EUR",
  MUS: "MUR",
  MWI: "MWK",
  MYS: "MYR",
  MYT: "EUR",
  NAM: "NAD",
  NCL: "XPF",
  NER: "XOF",
  NGA: "NGN",
  NIC: "NIO",
  NIU: "NZD",
  NLD: "EUR",
  NOR: "NOK",
  NPL: "NPR",
  NRU: "AUD",
  NZL: "NZD",
  OMN: "OMR",
  PAK: "PKR",
  PAN: "PAB",
  PCN: "NZD",
  PER: "PEN",
  PHL: "PHP",
  PLW: "USD",
  PNG: "PGK",
  POL: "PLN",
  PRK: "KPW",
  PRI: "USD",
  PRT: "EUR",
  PRY: "PYG",
  PYF: "XPF",
  QAT: "QAR",
  REU: "EUR",
  ROU: "RON",
  RUS: "RUB",
  RWA: "RWF",
  SAU: "SAR",
  SDN: "SDG",
  SEN: "XOF",
  SGP: "SGD",
  SHN: "SHP",
  SLB: "SBD",
  SLE: "SLE",
  SLV: "USD",
  SMR: "EUR",
  SOM: "SOS",
  SPM: "EUR",
  SRB: "RSD",
  SSD: "SSP",
  STP: "STN",
  SUR: "SRD",
  SVK: "EUR",
  SVN: "EUR",
  SWE: "SEK",
  SWZ: "SZL",
  SXM: "ANG",
  SYC: "SCR",
  SYR: "SYP",
  TCA: "USD",
  TCD: "XAF",
  TGO: "XOF",
  THA: "THB",
  TJK: "TJS",
  TKL: "NZD",
  TKM: "TMT",
  TLS: "USD",
  TON: "TOP",
  TTO: "TTD",
  TUN: "TND",
  TUR: "TRY",
  TUV: "AUD",
  TWN: "TWD",
  TZA: "TZS",
  UGA: "UGX",
  UKR: "UAH",
  URY: "UYU",
  USA: "USD",
  UZB: "UZS",
  VAT: "EUR",
  VCT: "XCD",
  VEN: "VES",
  VGB: "USD",
  VIR: "USD",
  VNM: "VND",
  VUT: "VUV",
  WBG: "ILS",
  WLF: "XPF",
  WSM: "WST",
  YEM: "YER",
  ZAF: "ZAR",
  ZMB: "ZMW",
  ZWE: "ZWG",
};

const currencyNamesByCode = {
  AWG: "Aruban florin",
  AFN: "Afghan afghani",
  XCD: "East Caribbean dollar",
  AOA: "Angolan kwanza",
  ALL: "Albanian lek",
  EUR: "Euro",
  AED: "United Arab Emirates dirham",
  ARS: "Argentine peso",
  AMD: "Armenian dram",
  USD: "United States dollar",
  AUD: "Australian dollar",
  AZN: "Azerbaijani manat",
  BIF: "Burundian franc",
  XOF: "West African CFA franc",
  BDT: "Bangladeshi taka",
  BGN: "Bulgarian lev",
  BHD: "Bahraini dinar",
  BSD: "Bahamian dollar",
  BAM: "Bosnia and Herzegovina convertible mark",
  BYN: "Belarusian ruble",
  BMD: "Bermudian dollar",
  BZD: "Belize dollar",
  BOB: "Boliviano",
  BRL: "Brazilian real",
  BBD: "Barbados dollar",
  BND: "Brunei dollar",
  BTN: "Bhutanese ngultrum",
  BWP: "Botswana pula",
  XAF: "Central African CFA franc",
  CAD: "Canadian dollar",
  CHF: "Swiss franc",
  CLP: "Chilean peso",
  CNY: "Renminbi",
  CDF: "Congolese franc",
  NZD: "New Zealand dollar",
  COP: "Colombian peso",
  KMF: "Comorian franc",
  CVE: "Cape Verdean escudo",
  CRC: "Costa Rican colon",
  CUP: "Cuban peso",
  ANG: "Netherlands Antillean guilder",
  KYD: "Cayman Islands dollar",
  CZK: "Czech koruna",
  DJF: "Djiboutian franc",
  DKK: "Danish krone",
  DOP: "Dominican peso",
  DZD: "Algerian dinar",
  EGP: "Egyptian pound",
  ERN: "Eritrean nakfa",
  ETB: "Ethiopian birr",
  FJD: "Fijian dollar",
  FKP: "Falkland Islands pound",
  GBP: "Pound sterling",
  GEL: "Georgian lari",
  GHS: "Ghanaian cedi",
  GIP: "Gibraltar pound",
  GNF: "Guinean franc",
  GMD: "Gambian dalasi",
  GTQ: "Guatemalan quetzal",
  GYD: "Guyanese dollar",
  HKD: "Hong Kong dollar",
  HNL: "Honduran lempira",
  HTG: "Haitian gourde",
  HUF: "Hungarian forint",
  IDR: "Indonesian rupiah",
  INR: "Indian rupee",
  IRR: "Iranian rial",
  IQD: "Iraqi dinar",
  ISK: "Icelandic króna",
  ILS: "Israeli new shekel",
  JMD: "Jamaican dollar",
  JOD: "Jordanian dinar",
  JPY: "Japanese Yen",
  KZT: "Kazakhstani tenge",
  KES: "Kenyan shilling",
  KGS: "Kyrgyzstani som",
  KHR: "Cambodian riel",
  KRW: "South Korean won",
  KWD: "Kuwaiti dinar",
  LAK: "Lao kip",
  LBP: "Lebanese pound",
  LRD: "Liberian dollar",
  LYD: "Libyan dinar",
  LKR: "Sri Lankan rupee",
  LSL: "Lesotho loti",
  MOP: "Macanese pataca",
  MAD: "Moroccan dirham",
  MDL: "Moldovan leu",
  MGA: "Malagasy ariary",
  MVR: "Maldivian rufiyaa",
  MXN: "Mexican peso",
  MKD: "Macedonian denar",
  MMK: "Myanmar kyat",
  MNT: "Mongolian tögrög",
  MZN: "Mozambican metical",
  MRU: "Mauritanian ouguiya",
  MUR: "Mauritian rupee",
  MWK: "Malawian kwacha",
  MYR: "Malaysian ringgit",
  NAD: "Namibian dollar",
  XPF: "CFP franc",
  NGN: "Nigerian naira",
  NIO: "Nicaraguan córdoba",
  NOK: "Norwegian krone",
  NPR: "Nepalese rupee",
  OMR: "Omani rial",
  PKR: "Pakistani rupee",
  PAB: "Panamanian balboa",
  PEN: "Peruvian sol",
  PHP: "Philippine peso",
  PGK: "Papua New Guinean kina",
  PLN: "Polish złoty",
  KPW: "North Korean won",
  PYG: "Paraguayan guaraní",
  QAR: "Qatari riyal",
  RON: "Romanian leu",
  RUB: "Russian ruble",
  RWF: "Rwandan franc",
  SAR: "Saudi riyal",
  SDG: "Sudanese pound",
  SGD: "Singapore dollar",
  SHP: "Saint Helena pound",
  SBD: "Solomon Islands dollar",
  SLE: "Sierra Leonean leone",
  SOS: "Somali shilling",
  RSD: "Serbian dinar",
  SSP: "South Sudanese pound",
  STN: "São Tomé and Príncipe dobra",
  SRD: "Surinamese dollar",
  SEK: "Swedish krona",
  SZL: "Swazi lilangeni",
  SCR: "Seychellois rupee",
  SYP: "Syrian pound",
  THB: "Thai baht",
  TJS: "Tajikistani somoni",
  TMT: "Turkmenistan manat",
  TOP: "Tongan paʻanga",
  TTD: "Trinidad and Tobago dollar",
  TND: "Tunisian dinar",
  TRY: "Turkish lira",
  TWD: "New Taiwan dollar",
  TZS: "Tanzanian shilling",
  UGX: "Ugandan shilling",
  UAH: "Ukrainian hryvnia",
  UYU: "Uruguayan peso",
  UZS: "Uzbekistani sum",
  VES: "Venezuelan sovereign bolívar",
  VND: "Vietnamese đồng",
  VUV: "Vanuatu vatu",
  WST: "Samoan tālā",
  YER: "Yemeni rial",
  ZAR: "South African rand",
  ZMW: "Zambian kwacha",
  ZWG: "Zimbabwe Gold",
  XCG: "Caribbean guilder",
};

export function getCurrencyCode(countryCode) {
  return currencyCodesByCountry[countryCode] ?? "";
}

export function getCurrencyName(currencyCode) {
  return currencyNamesByCode[currencyCode] ?? "";
}

export function getCountryCurrencyDisplay(countryCode) {
  const currencyCode = getCurrencyCode(countryCode);
  const currencyName = getCurrencyName(currencyCode);

  if (!currencyCode) {
    return "";
  }

  return currencyName ? `${currencyName} (${currencyCode})` : currencyCode;
}
