function defineDataSource(config) {
  return {
    ...config,
    rankingStaticDataPath: config.rankingStaticDataPath ?? config.staticDataPath.replace(/^\.\//, "../"),
  };
}

export const dataSources = {
  weoCurrentPrices: defineDataSource({
    dataSource: "IMF World Economic Outlook",
    dataset: "WEO",
    staticDataPath: "./data/weo/current-prices.json",
    rankingStaticDataPath: "../data/weo/rankings/current-prices/manifest.json",
    sourceUrl: "https://data.imf.org/-/media/iData/External-Storage/Documents/2F78EE59F79143A7921E5E203D3AAA80/en/WEOApr2026all.xlsx",
    startYear: 1980,
    endYear: 2026,
    subtitle: "IMF World Economic Outlook, 1980-2026",
  }),
  unctadTrade: defineDataSource({
    dataSource: "UNCTADstat",
    dataset: "UNCTAD Trade",
    staticDataPath: "./data/unctad/trade.json",
    rankingStaticDataPath: "../data/unctad/rankings/trade/manifest.json",
    sourceUrl: "https://unctadstat.unctad.org/datacentre/",
    startYear: 1948,
    endYear: 2025,
    subtitle: "UNCTADstat, 1948-2025",
  }),
  unctadServicesTrade: defineDataSource({
    dataSource: "UNCTADstat",
    dataset: "UNCTAD Services Trade",
    staticDataPath: "./data/unctad/services-trade.json",
    rankingStaticDataPath: "../data/unctad/rankings/services-trade/manifest.json",
    sourceUrl: "https://unctadstat.unctad.org/datacentre/",
    startYear: 2005,
    endYear: 2024,
    subtitle: "UNCTADstat, 2005-2024",
  }),
  worldBankWdi: defineDataSource({
    dataSource: "World Bank",
    dataset: "World Development Indicators",
    staticDataPath: "./data/world-bank/total-reserves.json",
    rankingStaticDataPath: "../data/world-bank/rankings/total-reserves/manifest.json",
    sourceUrl: "https://data.worldbank.org/indicator/FI.RES.TOTL.CD",
    startYear: 1960,
    endYear: 2024,
    subtitle: "World Bank World Development Indicators, 1960-2024",
  }),
  worldBankPopulation: defineDataSource({
    dataSource: "World Bank",
    dataset: "World Development Indicators",
    staticDataPath: "./data/world-bank/population-demographics.json",
    rankingStaticDataPath: "../data/world-bank/rankings/population-demographics/manifest.json",
    sourceUrl: "https://databank.worldbank.org/source/world-development-indicators",
    startYear: 1960,
    endYear: 2024,
    subtitle: "World Bank World Development Indicators, 1960-2024",
  }),
  worldBankEnvironment: defineDataSource({
    dataSource: "World Bank",
    dataset: "World Development Indicators",
    staticDataPath: "./data/world-bank/environment.json",
    rankingStaticDataPath: "../data/world-bank/rankings/environment/manifest.json",
    sourceUrl: "https://databank.worldbank.org/source/world-development-indicators",
    startYear: 1970,
    endYear: 2024,
    subtitle: "World Bank World Development Indicators, 1970-2024",
  }),
  ciaWorldFactbook: defineDataSource({
    dataSource: "CIA",
    dataset: "The World Factbook",
    staticDataPath: "./data/cia/area.json",
    rankingStaticDataPath: "../data/cia/rankings/area/manifest.json",
    sourceUrl: "https://www.cia.gov/the-world-factbook/",
    startYear: 2025,
    endYear: 2025,
    subtitle: "CIA World Factbook, 2025",
  }),
  sipriMilitarySpending: defineDataSource({
    dataSource: "SIPRI Military Expenditure Database",
    dataset: "SIPRI Military Spending",
    staticDataPath: "./data/sipri/military-spending.json",
    rankingStaticDataPath: "../data/sipri/rankings/military-spending/manifest.json",
    sourceUrl: "https://www.sipri.org/databases/milex",
    startYear: 1949,
    endYear: 2025,
    subtitle: "SIPRI Military Expenditure Database, 1949-2025",
  }),
};
