export const financeRankings = [
  {
    seriesId: "governmentGrossDebt",
    directory: "government-gross-debt",
    label: "Government Gross Debt (% of GDP)",
    countryPageKind: "government-debt",
    countryPageLabel: "Government Debt",
    profileSection: "Government Debt",
  },
  {
    seriesId: "governmentNetDebt",
    directory: "government-net-debt",
    label: "Government Net Debt (% of GDP)",
    countryPageKind: "government-debt",
    countryPageLabel: "Government Debt",
    profileSection: "Government Debt",
  },
  {
    seriesId: "fiscalBalance",
    directory: "fiscal-balance",
    label: "Fiscal Balance",
    countryPageKind: "fiscal-balance",
    profileSection: "Government Finance",
  },
  {
    seriesId: "primaryFiscalBalance",
    directory: "primary-fiscal-balance",
    label: "Primary Fiscal Balance",
    countryPageKind: "primary-fiscal-balance",
    profileSection: "Government Finance",
  },
  {
    seriesId: "governmentRevenue",
    directory: "government-revenue",
    label: "Government Revenue",
    countryPageKind: "government-revenue",
    profileSection: "Government Finance",
  },
  {
    seriesId: "governmentExpenditure",
    directory: "government-expenditure",
    label: "Government Expenditure",
    countryPageKind: "government-expenditure",
    profileSection: "Government Finance",
  },
  {
    seriesId: "totalReservesIncludingGold",
    directory: "total-reserves",
    label: "Total Reserves",
    countryPageKind: "total-reserves",
    profileSection: "International Reserves",
  },
];
